/** User-visible copy (single place for tone / future i18n) */
export const strings = {
  loadingCanvas: 'Loading canvas…',
  defaultProjectName: 'Untitled Project',
  theme: {
    switchToDark: 'Switch to dark mode',
    switchToLight: 'Switch to light mode',
    switchToGreen: 'Switch to green background',
    switchToBlue: 'Switch to blue-grey background',
  },
  sync: {
    connectFolder: 'Connect folder',
    sync: 'Sync',
    scanFolder: 'Scan folder',
    syncInProgress: 'Syncing with server…',
    syncInProgressWithFolder: 'Syncing with server and folder…',
    syncComplete: 'Sync finished.',
    syncTimedOut: 'Sync timed out. Try again or check the API server.',
    syncAlreadyInProgress: 'Sync already in progress. Wait a moment and try again.',
    serverDocumentMissing:
      'Project is on the server menu but has no canvas document yet. Edit the canvas here, then Sync again.',
    syncedFromServerRevision: (revision) =>
      `Synced from server (revision ${revision}).`,
    alreadySyncedRevision: (revision) =>
      `Already up to date with server (revision ${revision}).`,
    changeFolder: 'Change folder',
    nothingNew: 'Nothing new to sync',
    previewsRestored: 'Previews restored from folder',
    folderUnsupported: 'Folder access not supported in this browser. Use Chrome, Edge, or Arc.',
    reconnectFolder: 'Restore folder link and refresh the canvas',
    reconnectFolderAction: 'Restore folder link',
    reconnectFolderHint:
      'Your project folder is remembered. Restore the folder link to allow access again and refresh artefacts from disk.',
    reconnectFolderNamed: (name) =>
      `Restore the link to “${name}” and refresh artefacts from disk. Choose “Allow on every visit” in Chrome to avoid prompts when switching projects.`,
    repairFolderInProgress: 'Restoring folder link and refreshing artefacts…',
    repairFolderPickAgain:
      'Stored folder access could not be reused. Pick the folder again to repair and keep artefacts.',
    connectFolderNamed: (name) =>
      `This project uses folder “${name}” on another device. Pick that same folder once on this browser. The folder handle is saved here when the browser allows it.`,
    folderConnecting: 'Connecting folder…',
    folderPickerBusy:
      'Chrome still has a folder dialog open (check other windows) or refresh the page, then try Connect folder once.',
    folderPickerIdInvalid:
      'Could not open the folder picker. Refresh the page and try Connect folder again.',
    folderImportReady: (n) =>
      `${n} ${n === 1 ? 'artefact' : 'artefacts'} from folder — review and apply below.`,
    folderMissingCanvasArtifacts: (n) =>
      `${n} ${n === 1 ? 'artefact on the canvas is' : 'artefacts on the canvas are'} no longer in the connected folder. Remove ${n === 1 ? 'it' : 'them'} from the canvas or restore ${n === 1 ? 'the file' : 'the files'} and sync again.`,
    folderScanNoFiles:
      'Folder linked. No matching artefact files found (use prefix__name-v1.ext naming).',
    importedFilesFolderName: 'Imported files',
    importFiles: 'Import files',
    folderPermissionDenied: 'Could not access the folder. Try Reconnect or pick the folder again.',
    folderSaveFailed:
      'Folder connected for this session, but this browser could not save the folder link. Reconnect before refreshing the page.',
    primitivesNotUpdated: 'Saved to folder; primitives not updated (start API with npm run server).',
    serverSyncedConnectFolder:
      'Canvas synced from server. Connect a folder on this browser to sync files from disk.',
    serverSyncedConnectFolderNamed: (name) =>
      `Canvas synced from server. Connect folder “${name}” on this browser to sync files from disk.`,
    connectFolderAction: 'Connect folder',
    folderNameMismatch: (expected, actual) =>
      `Connected folder is “${actual}” but this project expects “${expected}”.`,
    artefact: 'artefact',
    artefacts: 'artefacts',
  },
  empty: {
    mobile: 'This canvas is empty.',
    mobileHint: 'Sync from a folder on your desktop to populate it.',
    desktopTitle: 'An empty canvas.',
    desktopHint: 'Connect a folder to begin',
    desktopHintReconnectFolder: (name) =>
      `Reconnect folder “${name}” on this browser to sync files from disk.`,
    desktopHintConnectFolderNamed: (name) =>
      `Connect folder “${name}” to sync files from disk.`,
  },
  preview: {
    noData: 'No data',
    notInProject: 'Preview not in saved project',
    resyncHint: 'Re-sync the folder to restore large previews',
    tooLarge: 'File too large to preview',
    doubleClickOpen: 'Double-click to open',
    doubleClickDownload: 'Double-click to download',
    loadingTranscript: 'Loading transcript…',
    transcriptUnavailable: 'Transcript not available — open in inspector.',
    loadingPdf: 'Loading PDF preview…',
    loadingPdfHint: 'Large file — preparing viewer',
    modalNotStored: 'Large preview not stored',
    modalResyncHint: 'Re-sync the connected folder to load this file again for a full preview.',
    modalTooLarge: 'File too large to preview inline',
  },
  card: {
    pinned: 'Pinned',
    versions: 'Versions',
    pinnedLabel: 'pinned',
    newer: 'newer',
    older: 'older',
    removeFromCanvas: 'Remove from canvas',
    remove: 'Remove',
    pinThisVersion: 'Pin this version',
    newerDraft: '· newer draft',
  },
  modal: {
    missingFromFolder:
      'No longer in the connected folder. Remove from canvas or restore the file and sync again.',
    versionPinned: '(pinned)',
    versionNewer: '(newer)',
    download: 'Download',
    artifactSidebar: 'Artifact annotations',
    artifactPrimitive: 'Artifact data',
    collapseSidebar: 'Hide annotations',
    expandSidebar: 'Show annotations',
    openExternal: 'Open in external app',
    openExternalFailed: 'Could not open file. Re-sync the folder or try again.',
    openExternalUnavailable: 'Connect a folder to open this file externally.',
    openExternalUseFolder:
      'Open "{filename}" from your connected folder "{folder}" in File Explorer to edit in Excel (browsers cannot launch desktop apps directly).',
    openExternalPopupBlocked:
      'Could not open a new tab. Allow pop-ups for this site, or open the file from your connected folder.',
    openExternalReconnect:
      'Click Sync to reconnect your folder, then try again.',
  },
  search: {
    label: 'Search',
    placeholder: 'Search artefacts…',
    noMatches: 'No matches',
  },
  changeFolder: {
    label: 'Folder',
    title: 'Connect a different folder',
    body: 'Choose whether to keep current artefacts on the canvas or start fresh before you pick a folder.',
    clearAndPick: 'Clear canvas and pick folder',
    keepAndPick: 'Keep artefacts, pick folder',
    cancel: 'Cancel',
  },
  syncConfirm: {
    label: 'Sync',
    changesFound: (n) => `${n} ${n === 1 ? 'change' : 'changes'} found`,
    new: 'new',
    versionsAdded: (n) => `+${n} version${n === 1 ? '' : 's'}`,
    cancel: 'Cancel',
    apply: 'Apply changes',
    replaceHint:
      'Applying replaces the canvas with synced items. New artefacts appear below for you to drag onto the canvas.',
    mergeHint:
      "New versions are added without changing what's pinned. New artefacts appear below — drag each circle onto the canvas to place it.",
  },
  syncHolding: {
    trayLabel: 'Artefacts waiting to place or dock',
    dragHint: 'Drag a circle onto the canvas to place, or drag a card here to dock',
    emptyTrayDrop: 'Drop card here',
    chipAria: (name, typeLabel) => `${name}, ${typeLabel}. Drag to canvas to place or dock from canvas.`,
  },
  canvas: {
    reset: 'Reset',
    resetTitle: 'Fit all cards in view',
    zoomPercentLabel: 'Canvas zoom percentage',
  },
  projects: {
    localOnlyBanner:
      'Projects are saved in this browser only. Start Postgres and the API (npm run server) to sync across browsers on this PC.',
    databaseUnavailable:
      'Database unavailable. Start Docker Desktop, then run npm run db:up and npm run db:migrate in the canvas folder, and restart npm run server.',
    loadFailed:
      'Could not load your canvas data. Check the browser console, then refresh. Large projects may finish syncing in the background after the canvas appears.',
    switchLoadFailed:
      'Could not load that project. Try again, or clear site storage if the browser is full.',
    noActiveProject:
      'Select or create a project before connecting a folder.',
    switchPushFailed:
      'Could not sync this project to the server yet. Your work is saved in this browser; try Sync or refresh from server before switching devices.',
    placementPushFailed:
      'Dock placement is saved in this browser only. Refreshing may move items back to the canvas until sync succeeds.',
    localStorageFull:
      'Browser storage is nearly full. Work still syncs to the server when the API is up. Clear local cache to free space (your projects on the server are kept).',
    clearLocalCache: 'Clear local cache',
    clearLocalCacheConfirm:
      'Remove cached project files from this browser? Projects on the server are not deleted. Requires API connection to reload.',
    clearLocalCacheUnavailable:
      'Cannot clear cache while offline — server reload is required to restore projects.',
    clearLocalCacheDone: 'Local cache cleared. Reloading from server…',
    storageBreakdown: (projectsMb, agentMb) =>
      `Cache ≈ ${projectsMb} MB projects, ${agentMb} MB agent chat (local only).`,
    syncingFromServer:
      'Syncing project from server…',
    syncedFromServer:
      'Canvas updated from server.',
    alreadySyncedFromServer:
      'Already up to date with the server.',
    loadingProject:
      'Loading project…',
    switchTimeout:
      'Project switch timed out. Try another project or click Sync to retry.',
    bootSyncTimeout:
      'Sync took too long; showing your cached canvas. Click Sync to retry from the server.',
    remoteChangesWhileEditing:
      'Changes on another device — click Sync to apply.',
    projectSyncConflict:
      'This project was changed on the server while you were editing.',
    useServerProjectCopy: 'Use server copy',
    keepMyProjectCopy: 'Keep my copy',
    serverRevisionStale:
      'A newer version of this project is on the server. Refresh to update before editing.',
    refreshFromServer: 'Reload from server',
    refreshProjects: 'Refresh projects',
    projectsRefreshed: 'Project list refreshed from server.',
    projectsRefreshFailed: 'Could not refresh projects from the server.',
    projectSyncing: 'Syncing project…',
    updatedFromOtherDevice:
      'This project was updated from the server.',
    projectIdHint: (id) => (id ? ` Project id: ${id}` : ''),
    mergedDuplicates: (n) =>
      `Removed ${n} duplicate project${n === 1 ? '' : 's'} with the same name.`,
    openInCursorToSync:
      'This browser has no projects yet. Open the app in the browser where your projects exist (with npm run server running), wait for “Migrated … to server storage” in the console, then refresh here.',
    recoveredFromBrowser: (n) =>
      `Restored ${n} project${n === 1 ? '' : 's'} from this browser and synced to server.`,
    purgedOrphanCaches: (n) =>
      `Removed ${n} unsynced project cache file${n === 1 ? '' : 's'} not in your workspace list.`,
    syncedProjectsFromServer: (n) =>
      `${n} project${n === 1 ? '' : 's'} synced from server into this workspace.`,
    duplicateNamesBanner: (name, count) =>
      `${count} projects named “${name}” — review in the Projects menu.`,
    emptyWorkspaceTitle: 'No projects yet',
    emptyWorkspaceBody:
      'Create a project to start placing notes, links, and files on the canvas. Projects are only added when you choose New project.',
    createFirstProject: 'Create your first project',
    selectProjectTitle: 'Choose a project',
    selectProjectBody:
      'You have projects in the menu but none is open yet. Pick a project from the Projects menu to load its canvas.',
    createTitle: 'New project',
    createNameLabel: 'Project name',
    createConfirm: 'Create',
    archiveLastTitle: 'Create another project?',
    archiveLastBody: (name) =>
      `“${name}” is archived and it was your only active project. Create a new project to continue, or pick another project from the menu.`,
    archiveLastCreateNew: 'New project',
    projectsMissingBody: (n) =>
      `${n} project${n === 1 ? '' : 's'} in the list ${n === 1 ? 'has' : 'have'} no saved canvas on this device or server — use Sync or open from the browser that has the data.`,
    switcherLabel: 'Projects',
    menuTitle: 'Projects',
    newProject: 'New project',
    archived: 'Archived',
    archivedEmpty: 'No archived projects',
    archive: 'Archive',
    unarchive: 'Restore',
    delete: 'Delete',
    deleteTitle: 'Delete project?',
    deleteBody: (name) =>
      `Delete “${name}” and all its artefacts? This removes the project from this workspace and the server. This cannot be undone.`,
    deleteConfirm: 'Delete',
    cancel: 'Cancel',
    cannotDeleteLast: 'You need at least one project.',
    deleteFailed: 'Could not delete this project. Try again.',
    deleteServerMayPersist:
      'Project removed on this device, but a server copy may still exist — sync will retry.',
    projectChangeInProgress:
      'Wait for the current project change to finish, then try again.',
    dockRestoreBanner: (n) =>
      `${n} item${n === 1 ? '' : 's'} in the sync dock — not on the canvas. Drag them on, or restore layout.`,
    dockRestoreAction: 'Restore to canvas',
    dockRestoredToast: (n) =>
      `Restored ${n} item${n === 1 ? '' : 's'} from the sync dock to the canvas.`,
    syncMissingBody: 'Canvas data missing on server — open in the browser that has this project to upload.',
    syncErrorBody: 'Could not sync this project (file may be too large for server storage).',
    active: 'Current project',
    viewPrimitives: 'View primitives',
    newNote: 'New note',
    addLink: 'Add link',
    createTask: 'Create task',
  },
  bookmark: {
    title: 'Add link',
    url: 'URL',
    urlPlaceholder: 'https://example.com',
    displayTitle: 'Title (optional)',
    previewLoading: 'Loading preview…',
    previewFailed: 'Could not load preview',
    previewOffline: 'Preview unavailable — you can still add this link.',
    enterUrl: 'Enter a URL to see a preview',
    save: 'Add to canvas',
    saving: 'Adding…',
    cancel: 'Cancel',
    open: 'Open link',
    link: 'Link',
    untitled: 'Untitled link',
    refreshPreview: 'Refresh preview',
    refreshingPreview: 'Refreshing…',
    saveEdit: 'Save',
    savingEdit: 'Saving…',
    savedProjectOnly: 'Saved to project. Connect a folder to sync this link to disk.',
    invalidUrl: 'Enter a valid URL (https://…).',
    primitivesNotUpdated: 'Link saved on canvas; primitives API was unavailable.',
  },
  userNote: {
    title: 'New note',
    prefix: 'Prefix',
    name: 'Name',
    body: 'Body',
    bodyPlaceholder: 'Write your note in markdown…',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    needFolder: 'Connect a folder with write access to create notes.',
    writeDenied: 'Folder is read-only. Reconnect the folder to allow saving notes.',
    editHint:
      'Saves to the connected folder. The title is the file name (notes__title-v1.md); renaming updates every version.',
    titleSaveHint: 'Press Save or click away from the title to apply a rename.',
    cannotSaveMissing: 'Cannot save — file is missing from the connected folder.',
    saveFailed: 'Could not save note.',
    tapToEdit: 'Click to edit',
    saveOnCard: 'Save',
    nameRequired: 'Note title cannot be empty.',
    nameInvalid: 'Title cannot contain \\ / : * ? " < > | or __.',
    nameCollision: 'A note with that title already exists in the folder.',
    connectToEdit: 'Connect and sync the project folder to edit this note.',
    savedProjectOnly: 'Saved to project. Connect a folder to write notes to disk.',
    zoomToEdit: 'Zoom in to edit on the canvas.',
  },
  linkArtifact: {
    title: 'Link to artifact',
    search: 'Search artifacts…',
    empty: 'No other artifacts on the canvas with a synced artifact ref.',
    link: 'Link',
  },
  flow: {
    inspectorConnection: 'Connection',
    connectionFrom: 'From',
    connectionTo: 'To',
    connectionFlowsFrom: 'Flows from',
    connectionFlowsTo: 'Flows to',
    connectionFlow: 'Animate flow',
    connectionFlowHint: 'Shows a moving dashed stroke along the connection.',
    reverseDirection: 'Reverse direction',
    reverseDirectionHint: 'Flip which way this connection flows.',
    removeConnection: 'Remove connection',
    removeNode: 'Remove node',
    connectionHint: 'Select a connection, then press Delete or use the button above.',
    connectionType: 'Connection type',
    connectionTypeCustom: 'Custom label',
    connectionTypeDetail: 'Detail',
    connectionTypeDetailPlaceholder: 'e.g. Love',
    connectionLabelPreview: (label) => `Label: ${label}`,
    connectionTypeUnspecified: 'Unspecified',
    connectionProperties: 'Properties',
    connectionPropertiesEmpty: 'No properties yet.',
    connectionPropertyKey: 'Key',
    connectionPropertyValue: 'Value',
    connectionAddProperty: 'Add property',
    connectionRemoveProperty: 'Remove property',
    nodeHint: 'Select a node, then press Delete or use the button above.',
    connectionRemoved: 'Connection removed.',
    selectNodeOrConnection: 'Select a node or connection to inspect it.',
    collapseInspector: 'Hide inspector',
    expandInspector: 'Show inspector',
    showContent: 'Show content',
    hideContent: 'Hide content',
    previewUnavailable: 'Source artifact is no longer on the canvas.',
    localPreviewEmpty: 'No description to preview.',
  },
  graph: {
    linked: 'Linked',
    outgoing: 'Links to',
    referencedBy: 'Referenced by',
    notesOnArtifact: 'Interpretation notes',
    linkBadge: (n) => `${n} link${n === 1 ? '' : 's'}`,
    dragToLink: 'Drag to link to another card',
    linkConfirm: (name) => `Link note to “${name}”?`,
    relationType: 'Relationship type',
    unlink: 'Remove link',
    deleteLink: 'Remove link',
    openRelationship: 'View relationship',
    openNoteLink: 'View note',
    linkDeleted: 'Link removed.',
    linkDeleteFailed: 'Could not remove link.',
    noteDeleteFailed: 'Could not remove note attachment.',
    linkTargets: 'Link to cards',
    linkNeedsRefs:
      'Save cards to the connected folder and keep the API running before linking.',
    linkNeedsCluster: 'Workspace graph is not ready yet. Try Sync or refresh.',
    linkCreateFailed: 'Could not create link.',
  },
  cluster: {
    createFromSelection: 'Create cluster from selection',
    create: 'Create cluster',
    creating: 'Creating…',
    name: 'Cluster name',
    purpose: 'Purpose (optional)',
    members: 'Members',
    removeMember: 'Remove from cluster',
    parentCluster: 'Parent workspace',
    viewParent: 'View workspace cluster',
    noArtifactsSelected: 'No synced artifacts in selection — sync cards first.',
    selectionSummary: (selected, syncable) =>
      `${selected} card${selected === 1 ? '' : 's'} selected, ${syncable} with synced artifacts.`,
    created: 'Cluster created.',
    createFailed: 'Could not create cluster.',
    createApiUnavailable:
      'Clusters need Postgres. Start Docker Desktop, then run npm run db:up && npm run db:migrate and npm run server.',
    apiUnreachableBanner:
      'Clusters unavailable — cannot reach the API server. Run npm run server (port 3001).',
    dbUnavailableBanner:
      'Clusters unavailable — database not ready. Run npm run db:up && npm run db:migrate, then restart npm run server.',
    hullsLoadFailed: 'Could not load clusters from the server.',
    workspaceClusterFailed:
      'Could not create or load the workspace cluster for this project.',
    groupFromSelection: 'Group selection',
    shiftClickHint: 'Shift+click cards to multi-select',
    moveHandle: 'Move cluster',
    canvasLabel: (name) => `Cluster: ${name}`,
    renameFailed: 'Could not rename cluster.',
    renameApiUnavailable:
      'Rename failed — restart the API server (npm run server) and try again.',
    nameSaving: 'Saving…',
    addSelection: 'Add selection to cluster',
    addingMembers: 'Adding…',
    membersAdded: 'Added to cluster.',
    addMembersFailed: 'Could not add to cluster.',
    deleteCluster: 'Delete cluster',
    deleteClusterConfirm: 'Delete this cluster? Members stay on the canvas; grouping is removed.',
    deleting: 'Deleting…',
    deleted: 'Cluster deleted.',
    deleteFailed: 'Could not delete cluster.',
    cannotDeleteWorkspace: 'The workspace cluster cannot be deleted.',
    viewArtifactDetails: 'View artifact details',
  },
  agent: {
    title: 'Agent mode',
    panelSectionSetup: 'Setup',
    panelSectionConversation: 'Threads & chat',
    modeLabel: 'Mode',
    modeMultiAgent: 'Multi-agent panel',
    modeSingleAgent: 'Single agent',
    connectorHeading: 'Agent',
    apiKeyHeading: 'API key',
    apiKeyLabel: 'OpenAI API key',
    apiKeyPlaceholder: 'sk-…',
    apiKeySave: 'Save key',
    apiKeyReplace: 'Replace key',
    apiKeyRemove: 'Remove key',
    apiKeyCancel: 'Cancel',
    apiKeyConfigured: (hint) => `Configured (${hint})`,
    apiKeyMissing: 'Add an API key to chat with this agent.',
    apiKeySaving: 'Saving…',
    apiKeySaved: 'API key saved.',
    apiKeyRequired: 'Enter an API key.',
    apiKeySaveFailed: 'Could not save the API key.',
    apiKeyConnectorUnavailable: 'No agent connector is available.',
    apiOffline:
      'Cannot reach the API. Start it with npm run server in the canvas folder.',
    secretsNotConfigured:
      'Server cannot store keys. Restart the API (npm run server) so it can create canvas/.data/agent-master.key.',
    credentialNotUsable:
      'A saved key exists but cannot be unlocked. Use Replace in the menu below and save your API key again.',
    localAgentReady: 'Local Ollama agent is ready.',
    localAgentUnavailable:
      'Start Ollama on localhost:11434 and pull the selected model before chatting.',
    retryConnectors: 'Retry connection',
    threadAgentTypeIncompatible: (label) =>
      `Change this thread to ${label} before chatting with the selected agent.`,
    threadsActiveLabel: 'Active thread',
    threadsHeading: 'Threads',
    threadsNew: 'New thread',
    threadsSwitch: 'Switch thread',
    threadsRename: 'Rename',
    threadsRenameSave: 'Save',
    threadsDelete: 'Delete',
    threadsEmpty: 'No threads yet. Start a new thread to chat.',
    threadsPickerHint: 'Choose a thread to continue or start a new conversation.',
    threadsDeleteConfirm:
      'Delete this thread? Messages are removed from the panel; the transcript file on disk is kept unless you remove the canvas card.',
    chatHeading: 'Chat',
    chatThinking: 'Thinking…',
    chatEmptyHint: 'Send a message to start the conversation.',
    threadContextHeading: 'In context for this thread',
    threadContextEmpty:
      'No files in context yet — select artefacts on the canvas to add them.',
    threadContextPending: 'sends on next message',
    threadContextRestored: 'Context restored from this thread.',
    chatError: 'Could not get a reply.',
    openaiUnreachable:
      'The API server cannot verify HTTPS to OpenAI on this PC. Stop the server and start it again with npm run server (uses Windows certificate store). If it still fails, check antivirus HTTPS scanning or firewall.',
    agentsHeading: (n) => `Agents (${n})`,
    addAgent: 'Add agent',
    addAgentComingSoon: 'Custom agents coming soon.',
    contextHeading: 'Context',
    contextSelected: 'Selected items',
    contextSelectedHint: (n) => `Focus on ${n} item${n === 1 ? '' : 's'}`,
    contextSelectedEmpty: 'Click cards on the canvas to add them',
    contextSelectedEmptyShift: 'Shift+click cards to multi-select',
    contextArtifact: 'This artifact',
    contextArtifactHint: 'Agent context is locked to the open artifact.',
    contextFlow: 'This workflow',
    contextFlowHint: 'Select nodes in the flow editor to scope the diagram. Artifact nodes in scope are sent as file context.',
    contextFlowIncludeNetwork: 'Include connected network',
    contextFlowSelectionSummary: (nodes, edges) => `${nodes} node${nodes === 1 ? '' : 's'}, ${edges} connection${edges === 1 ? '' : 's'}`,
    contextFlowFullDiagram: 'Full diagram (no nodes selected)',
    askAboutFlow: 'Discuss workflow with Agent',
    contextListHeading: 'In context',
    contextRemoveItem: 'Remove from context',
    contextIncluded: 'included',
    contextSentAsImage: 'sends as image',
    contextImageTooLarge: 'image too large',
    contextPending: 'on send',
    contextSentToAi: 'Sent to AI',
    contextSendsOnNextMessage: 'Sends on next message',
    contextUpdatedResend: 'Updated — resends on next message',
    contextPendingAddBanner: (n, names) =>
      `${n} file${n === 1 ? '' : 's'} will be sent to the AI with your next message${names ? `: ${names}` : ''}.`,
    contextPendingRemoveBanner: (n, names) =>
      `${n} file${n === 1 ? '' : 's'} removed from selection. The AI will be told on your next message${names ? `: ${names}` : ''}.`,
    contextFilesAddedToast: (n) => `Sent ${n} file${n === 1 ? '' : 's'} to AI.`,
    contextFilesRemovedToast: (n) =>
      `Notified AI: ${n} file${n === 1 ? '' : 's'} removed from context.`,
    contextRefresh: 'Resend all selected files to AI',
    contextRefreshConfirm:
      'Clear cached context and resend all selected files on your next message. Continue?',
    contextChatAddLabel: (names) => `Sent to AI: ${names}`,
    contextChatRemoveLabel: (names) => `Removed from context: ${names}`,
    agentChatViewTranscript: 'View transcript in inspector',
    agentChatClear: 'Clear chat',
    agentChatClearConfirm: 'Clear this chat thread from the panel? The workspace transcript artifact is kept.',
    agentChatCleared: 'Chat cleared.',
    agentChatPersistTrimmed:
      'Older messages were trimmed from local storage to stay within size limits.',
    agentChatTranscriptSyncFailed:
      'Chat saved locally; transcript could not sync to workspace (API offline).',
    agentChatTranscriptIngestFailed:
      'Chat saved locally; transcript could not sync to workspace (check API server logs).',
    agentChatTranscriptFolderWriteFailed:
      'Chat saved to workspace, but the linked folder denied write access. Reconnect the folder and retry sync.',
    agentChatTranscriptFolderWriteDenied:
      'Could not write chat transcript to the linked folder. Re-grant folder write access and retry sync.',
    agentChatRetrySync: 'Retry workspace sync',
    agentChatRetrySuccess: 'Chat transcript synced to workspace.',
    agentChatRetryFailed: 'Workspace sync still failed. Check API server and Postgres.',
    agentChatRetryFolderFailed:
      'Folder export still failed. Reconnect the project folder and grant write access.',
    contextNeedsFolder: 'needs folder',
    contextNoContent: 'no content',
    contextReconnectFolder:
      'Reconnect the project folder so the agent can read PDF and file content.',
    contextReconnectFolderNamed: (name) =>
      `Reconnect to “${name}” on this browser so the agent can read files (one-time per browser).`,
    contextConnectFolder:
      'Connect a project folder on this browser so the agent can read PDF, image, and file content.',
    contextConnectFolderNamed: (name) =>
      `Connect folder “${name}” on this browser so the agent can read files.`,
    contextLoading: 'Loading file content…',
    contextPdfExtractFailed: 'Could not extract text from this PDF.',
    contextExtendedLabel: 'Extended context',
    contextExtendedHint:
      'Sends more PDF pages and text (up to 100 pages / 110k chars). Slower and uses more API tokens.',
    contextLargeFileWarning: (label, pages, profilePages) =>
      `Large file “${label}” (${pages} pages). Standard mode sends the first ${profilePages} pages only.`,
    contextTruncatedAfterSend: (summary) =>
      `Some context was truncated: ${summary}`,
    contextTokenEstimate: (tokens, usd) =>
      `Estimated input: ~${tokens.toLocaleString()} tokens (~$${usd.toFixed(4)}). Reply billed separately.`,
    contextTokenEstimateLoading: 'Calculating token estimate…',
    contextLargeTokenConfirm: (tokens, usd) =>
      `This message will use about ${tokens.toLocaleString()} input tokens (~$${usd.toFixed(4)}). Continue?`,
    contextMessageSummary: (mode, n, labels) => {
      const kind =
        mode === 'visible'
          ? 'visible canvas'
          : mode === 'artifact'
            ? 'open artifact'
            : 'selected items';
      if (n === 0) return `Context: no ${kind}`;
      const preview = labels.length ? labels.slice(0, 3).join(', ') : '';
      const more = labels.length > 3 ? ` +${labels.length - 3} more` : '';
      return `Context: ${n} ${kind}${preview ? ` (${preview}${more})` : ''}`;
    },
    contextVisible: 'Visible canvas',
    contextVisibleHint: 'Include all visible items',
    inputPlaceholder: 'Ask agents anything about your canvas…',
    send: 'Send',
    disclaimer: 'Agents can make mistakes. Verify important info.',
    openAgentMode: 'Agent mode',
    askAboutArtifact: 'Ask Agent about this artifact',
    toggleAgent: 'Agent mode',
  },
  assertion: {
    title: 'Add claim',
    predicatePlaceholder: 'Predicate (e.g. describes)',
    objectPlaceholder: 'Object (optional literal)',
    add: 'Add claim',
    saving: 'Saving…',
    added: 'Claim added.',
    apiUnavailable: 'Claims require the primitives API (npm run server).',
  },
  task: {
    createTitle: 'Create task',
    intent: 'Intent',
    type: 'Type',
    create: 'Create',
    saving: 'Saving…',
    cancel: 'Cancel',
    linkedInputs: (n) => `${n} artifact input${n === 1 ? '' : 's'} linked`,
  },
  inspector: {
    title: 'Primitive',
    viewPrimitives: 'Primitives in project',
    viewArtifact: 'View artifact',
    empty: 'No primitives yet — sync a folder to ingest artifacts.',
    emptyNoCluster: 'No project cluster yet — sync or create a note to register primitives.',
    emptyApiOffline: 'Primitives API offline — run npm run server.',
    loading: 'Loading…',
    edges: 'Relationships',
    provenance: 'Provenance',
    openOnCanvas: 'Zoom to artifact',
    openInInspector: 'Open in inspector',
    payloadPreview: 'Content preview',
  },
  audio: {
    play: 'Play',
    pause: 'Pause',
    stop: 'Stop',
    scrub: 'Seek',
    untitled: 'Untitled track',
    title: 'Title',
    artist: 'Artist',
    album: 'Album',
    duration: 'Duration',
    genre: 'Genre',
    year: 'Year',
    track: 'Track',
    noPreview: 'Audio preview unavailable',
  },
  audioSkin: {
    title: 'Background colour',
    pickColor: 'Change audio background colour',
    close: 'Close colour picker',
    favorites: 'Favourites',
    custom: 'Custom',
    addFavorite: 'Add to favourites',
    removeFavorite: 'Remove from favourites',
    addCurrentToFavorites: 'Save current colour to favourites',
    setDefault: 'Set as default for new audio cards',
    clearDefault: 'Clear default colour',
  },
  artifactNotes: {
    title: 'Notes on this artifact',
    placeholder: 'Add an interpretation (markdown)…',
    add: 'Add note',
    empty: 'No notes yet.',
    apiUnavailable: 'Notes require the primitives API (run npm run server).',
  },
  architecture: {
    open: 'System architecture',
    close: 'Close',
    title: 'Canvas system architecture',
    subtitle: (version) => `Spec ${version} — placement, auto-reconcile sync, notes, and data stores`,
    diagramTitle: 'Layers',
    featuresTitle: 'Key features',
    entityStorageTitle: 'Where data lives',
    entityStorageServer: 'Server (Postgres / API)',
    entityStorageClient: 'Browser (local)',
    copyPreviewTitle: 'Copy for AI (preview)',
    copy: 'Copy for AI',
    copied: 'Copied',
    copyFailed: 'Copy failed',
    statusCurrent: 'current',
    statusTarget: 'target',
    roadmapTitle: 'Load performance roadmap',
    runtimeTitle: 'Runtime snapshot',
  },
  workspaceTree: {
    title: 'Workspace',
    toggle: 'Workspace tree',
    projectView: 'Project',
    allProjectsView: 'All projects',
    allProjectsTitle: 'All Projects',
    viewModeLabel: 'Workspace view',
    legend: 'Type key',
    placementLegend: 'Placement',
    placementCanvas: 'On canvas',
    placementDock: 'In dock',
    placementCanvasShort: 'Canvas',
    placementDockShort: 'Dock',
    loading: 'Loading workspace…',
    empty: 'No primitives in this project yet.',
    emptyAllProjects: 'No primitives across projects yet.',
    emptyNoCluster: 'No project cluster yet — sync or create a note to register primitives.',
    apiRequired: 'Workspace tree requires the primitives API (run npm run server).',
    close: 'Close workspace tree',
  },
};
