import { defineNode, definePipe } from './architectureGraphSchema.js';

export const ARCHITECTURE_GRAPH_NODES = [
  defineNode({
    id: 'canvas',
    label: 'Canvas',
    layer: 'client-ui',
    component: 'Infinite canvas workspace',
    purpose: 'Renders cards, handles drag, pan, zoom, and selection.',
    why: 'Primary spatial UI for project artifacts.',
    triggers: ['Project load', 'Card drag', 'Right-click add menu'],
    codeRef: 'src/components/Canvas.jsx',
    functions: ['Canvas'],
    inputs: [{ name: 'state', type: 'CanvasProjectState' }],
    outputs: [{ name: 'layoutEvents', type: 'CardPositionCommit[]' }],
  }),
  defineNode({
    id: 'addMenu',
    label: 'Add menu',
    layer: 'client-ui',
    component: 'Add + dropdown',
    purpose: 'Entry point for creating beat, agent, live, flow, studio, link, task, note cards.',
    why: 'Consolidates seven create actions into one menu.',
    triggers: ['Toolbar Add click', 'Canvas context menu'],
    codeRef: 'src/components/AddMenu.jsx',
    functions: ['AddMenu', 'handleAddMenuSelect'],
    inputs: [{ name: 'folderLinked', type: 'boolean' }],
    outputs: [{ name: 'dialogOpen', type: 'CreateDialogId' }],
  }),
  defineNode({
    id: 'newTaskDialog',
    label: 'New task dialog',
    layer: 'client-ui',
    component: 'Task creation modal',
    purpose: 'Collects task name, body, status before save.',
    why: 'Folder-backed tasks require user input before file write.',
    triggers: ['Add menu → Add task'],
    codeRef: 'src/components/NewTaskDialog.jsx',
    inputs: [{ name: 'values', type: 'NewTaskFormValues' }],
    outputs: [{ name: 'onSave', type: 'handleSaveNewTask payload' }],
  }),
  defineNode({
    id: 'newNoteDialog',
    label: 'New note dialog',
    layer: 'client-ui',
    component: 'Note creation modal',
    purpose: 'Collects note prefix, name, body before save.',
    why: 'Folder-backed notes require user input before file write.',
    triggers: ['Add menu → Add note'],
    codeRef: 'src/components/NewNoteDialog.jsx',
    inputs: [{ name: 'values', type: 'NewNoteFormValues' }],
    outputs: [{ name: 'onSave', type: 'handleSaveNewNote payload' }],
  }),
  defineNode({
    id: 'syncHoldingTray',
    label: 'Sync holding tray',
    layer: 'client-ui',
    component: 'Dock for staged cards',
    purpose: 'Shows stagedSyncCards awaiting placement on canvas.',
    why: 'Separates folder discoveries and agent chats from canvas until placed.',
    triggers: ['Folder scan', 'Agent chat staging', 'Drag from canvas to dock'],
    codeRef: 'src/components/SyncHoldingTray.jsx',
    inputs: [{ name: 'stagedSyncCards', type: 'StagedSyncCard[]' }],
    outputs: [{ name: 'placeOnCanvas', type: 'placeStagedCardOnCanvas' }],
  }),
  defineNode({
    id: 'syncConfirm',
    label: 'SYNC confirm',
    layer: 'client-ui',
    component: 'Folder diff confirmation dialog',
    purpose: 'Lists new/changed files from disk for user approval.',
    why: 'Prevents silent ingest of unexpected folder changes.',
    triggers: ['Footer Sync when disk has new non-agent files'],
    codeRef: 'src/components/SyncConfirm.jsx',
    inputs: [{ name: 'changes', type: 'SyncChange[]' }],
    outputs: [{ name: 'applySyncChanges', type: 'void' }],
  }),
  defineNode({
    id: 'canvasChrome',
    label: 'Canvas chrome',
    layer: 'client-ui',
    component: 'Toolbar and footer',
    purpose: 'Project switcher, sync footer, zoom, Add menu host.',
    why: 'Global workspace controls outside the canvas surface.',
    triggers: ['Always visible on desktop'],
    codeRef: 'src/components/CanvasChrome.jsx',
    inputs: [{ name: 'syncStatus', type: 'SyncStatus' }],
    outputs: [{ name: 'onSync', type: 'handleSyncClick' }],
  }),
  defineNode({
    id: 'agentPanel',
    label: 'Agent panel',
    layer: 'client-ui',
    component: 'Agent chat side panel',
    purpose: 'Connector picker, thread UI, chat send.',
    why: 'Isolated agent conversation surface in right dock.',
    triggers: ['Agent mode toggle'],
    codeRef: 'src/components/AgentSidePanel.jsx',
    inputs: [{ name: 'message', type: 'string' }],
    outputs: [{ name: 'transcript', type: 'AgentChatTranscript' }],
  }),
  defineNode({
    id: 'agentControlRoom',
    label: 'Agent control room',
    layer: 'client-ui',
    component: 'Image agent card modal',
    purpose: 'Prompt, references, provider settings, and Run for image agents.',
    why: 'Structured agent cards execute server-side transformers from the card modal.',
    triggers: ['Open agent card', 'Run image generation'],
    codeRef: 'src/features/agents/components/AgentControlRoom.jsx',
    inputs: [{ name: 'settings', type: 'ImageAgentSettings' }],
    outputs: [{ name: 'execution', type: 'Execution' }],
  }),
  defineNode({
    id: 'createStudioDialog',
    label: 'Create studio dialog',
    layer: 'client-ui',
    component: 'Studio creation modal',
    purpose: 'Collects studio title and playbook before POST /studios.',
    why: 'Studios are composite artifacts with surfaces created server-side.',
    triggers: ['Add menu → Add studio'],
    codeRef: 'src/features/studio/components/CreateStudioDialog.jsx',
    inputs: [{ name: 'title', type: 'string' }],
    outputs: [{ name: 'onSave', type: 'CreateStudioInput' }],
  }),
  defineNode({
    id: 'createSonicStudioDialog',
    label: 'Create sonic studio dialog',
    layer: 'client-ui',
    component: 'Sonic Studio creation modal',
    purpose: 'Collects Sonic Studio name before appending a sonic_studio card to project JSON.',
    why: 'Sonic studios are client-authored music cards, not nested server studios.',
    triggers: ['Add menu → Add Sonic Studio'],
    codeRef: 'src/features/sonicStudio/components/CreateSonicStudioDialog.jsx',
    inputs: [{ name: 'name', type: 'string' }],
    outputs: [{ name: 'onSave', type: 'CreateSonicStudioInput' }],
  }),
  defineNode({
    id: 'studioDashboard',
    label: 'Studio dashboard',
    layer: 'client-ui',
    component: 'Studio workspace UI',
    purpose: 'Surfaces, child studios, archive/restore, promotion queue, opens primary Exploration.',
    why: 'Studios are edited outside the infinite canvas card modal.',
    triggers: ['Open studio card', 'Navigate parent/child breadcrumb'],
    codeRef: 'src/features/studio/components/StudioDashboard.jsx',
    inputs: [{ name: 'overview', type: 'StudioOverview' }],
    outputs: [{ name: 'pendingRestoreStudio', type: 'RestoreProjectionRequest' }],
  }),
  defineNode({
    id: 'flowEditor',
    label: 'Flow editor',
    layer: 'client-ui',
    component: 'Exploration editor',
    purpose: 'Edits flow nodes/edges; invokes child studios and projects studio nodes on parent surface.',
    why: 'Primary Exploration surface for domain studios.',
    triggers: ['Open studio primary surface', 'Open flow card'],
    codeRef: 'src/features/flow/components/FlowEditor.jsx',
    inputs: [{ name: 'flowId', type: 'uuid' }],
    outputs: [{ name: 'flowSave', type: 'FlowDocumentPayload' }],
  }),
  defineNode({
    id: 'useCanvasDocument',
    label: 'useCanvasDocument',
    layer: 'client-hooks',
    component: 'Canvas document hook',
    purpose: 'Owns cards state, save handlers, structural mutations.',
    why: 'Central mutation API for canvas cards and folder-backed creates.',
    triggers: ['Create/save note/task/link', 'Card delete', 'Inline saves'],
    codeRef: 'src/features/canvas/useCanvasDocument.js',
    functions: ['handleSaveNewTask', 'handleSaveNewNote', 'handleSaveNewLink'],
    inputs: [{ name: 'projectId', type: 'uuid' }, { name: 'folderHandle', type: 'FileSystemDirectoryHandle' }],
    outputs: [{ name: 'state', type: 'CanvasProjectState' }],
  }),
  defineNode({
    id: 'useProjectSyncLifecycle',
    label: 'useProjectSyncLifecycle',
    layer: 'client-hooks',
    component: 'Project sync lifecycle hook',
    purpose: 'Boot, switch, visibility resume, reconcile orchestration.',
    why: 'Keeps browser cache converged with server document authority.',
    triggers: ['Project switch', 'Tab visibility', 'Manual refresh'],
    codeRef: 'src/features/sync/useProjectSyncLifecycle.js',
    functions: ['applyReconcileFromServer'],
    inputs: [{ name: 'projectId', type: 'uuid' }],
    outputs: [{ name: 'reconcileResult', type: 'ReconcileOutcome' }],
  }),
  defineNode({
    id: 'useActionSync',
    label: 'useActionSync',
    layer: 'client-hooks',
    component: 'Action sync hook',
    purpose: 'Wires pointer-up layout commit and placement transfer to push pipeline.',
    why: 'Debounced, action-based sync instead of timer polling during drag.',
    triggers: ['Card drag end', 'Canvas view commit', 'Dock placement'],
    codeRef: 'src/features/sync/useActionSync.js',
    functions: ['handleInteractionCommit', 'requestPlacementSync'],
    inputs: [{ name: 'reason', type: 'string' }],
    outputs: [{ name: 'commitProjectDocument', type: 'Promise' }],
  }),
  defineNode({
    id: 'resolveAgentReferenceImages',
    label: 'resolveAgentReferenceImages',
    layer: 'client-hooks',
    component: 'Reference image resolver',
    purpose: 'Loads reference image bytes from folder, preview cache, or artifact payload.',
    why: 'Image agents send transient referenceImages on execute without persisting them to project JSON.',
    triggers: ['Run image agent'],
    codeRef: 'src/features/agents/domain/referenceImages.js',
    inputs: [{ name: 'referenceArtifactIds', type: 'uuid[]' }],
    outputs: [{ name: 'referenceImages', type: 'ReferenceImage[]' }],
  }),
  defineNode({
    id: 'completeAgentImageGeneration',
    label: 'completeAgentImageGeneration',
    layer: 'client-hooks',
    component: 'Image generation completion',
    purpose: 'Writes PNGs to folder, places cards, wires agent→image relationships.',
    why: 'Client finishes the run after server returns generated image artifacts.',
    triggers: ['Successful agent execute response'],
    codeRef: 'src/features/agents/domain/completeAgentImageGeneration.js',
    inputs: [{ name: 'outputs', type: 'GeneratedImageArtifact[]' }],
    outputs: [{ name: 'cards', type: 'CanvasCard[]' }],
  }),
  defineNode({
    id: 'createUserTask',
    label: 'createUserTask',
    layer: 'client-sync',
    component: 'Task ingest pipeline',
    purpose: 'Writes tasks__ file, builds card, queues primitive ingest.',
    why: 'Folder-backed user_task cards need atomic file + card creation.',
    triggers: ['New task dialog save'],
    codeRef: 'src/lib/ingest/createUserTask.js',
    functions: ['createUserTaskArtifact'],
    inputs: [{ name: 'name', type: 'string' }, { name: 'taskStatus', type: 'important|general' }],
    outputs: [{ name: 'card', type: 'CanvasCard' }, { name: 'ingest', type: 'IngestResult' }],
  }),
  defineNode({
    id: 'createUserNote',
    label: 'createUserNote',
    layer: 'client-sync',
    component: 'Note ingest pipeline',
    purpose: 'Writes notes__ file, builds card, queues primitive ingest.',
    why: 'Folder-backed user_note cards need atomic file + card creation.',
    triggers: ['New note dialog save'],
    functions: ['createUserNoteArtifact'],
    codeRef: 'src/lib/ingest/createUserNote.js',
    inputs: [{ name: 'name', type: 'string' }, { name: 'body', type: 'string' }],
    outputs: [{ name: 'card', type: 'CanvasCard' }, { name: 'ingest', type: 'IngestResult' }],
  }),
  defineNode({
    id: 'artifactPlacement',
    label: 'artifactPlacement',
    layer: 'client-sync',
    component: 'Placement exclusivity engine',
    purpose: 'Enforces canvas XOR dock per canonical sync key.',
    why: 'Single surface per artifact prevents duplicate cards.',
    triggers: ['Load normalize', 'Dock/canvas moves', 'Folder scan heal'],
    codeRef: 'src/lib/artifactPlacement.js',
    functions: ['moveToCanvas', 'moveToDock', 'enforceExclusivePlacement'],
    inputs: [{ name: 'key', type: 'CanonicalSyncKey' }],
    outputs: [{ name: 'surface', type: 'canvas|dock' }],
  }),
  defineNode({
    id: 'artifactPlacementsMap',
    label: 'artifactPlacementsMap',
    layer: 'client-sync',
    component: 'Placement map v2',
    purpose: 'Persists slim placement refs alongside card records.',
    why: 'SSOT for surface without duplicating full card payloads.',
    triggers: ['Project save', 'Load migration'],
    codeRef: 'src/lib/artifactPlacementsMap.js',
    functions: ['attachArtifactPlacementsToPayload', 'reconcileArtifactPlacements'],
    inputs: [{ name: 'cards', type: 'CanvasCard[]' }, { name: 'staged', type: 'StagedSyncCard[]' }],
    outputs: [{ name: 'artifactPlacements', type: 'ArtifactPlacementsMap v2' }],
  }),
  defineNode({
    id: 'syncStaging',
    label: 'syncStaging',
    layer: 'client-sync',
    component: 'Folder scan staging',
    purpose: 'Diffs disk vs canvas+dock; builds SYNC confirm lists.',
    why: 'Path-aware identity for folder-backed artifacts.',
    triggers: ['Footer Sync scanFolder'],
    codeRef: 'src/lib/syncStaging.js',
    functions: ['buildSyncChangesFromFolder', 'placeStagedCardOnCanvas'],
    inputs: [{ name: 'folderScan', type: 'FolderScanResult' }],
    outputs: [{ name: 'stagedSyncCards', type: 'StagedSyncCard[]' }],
  }),
  defineNode({
    id: 'actionSync',
    label: 'actionSync',
    layer: 'client-sync',
    component: 'Action sync coordinator',
    purpose: 'Serializes layout, structural, and scan pushes.',
    why: 'Prevents overlapping pushes and race conditions.',
    triggers: ['Interaction commit', 'Structural change', 'Folder scan complete'],
    codeRef: 'src/lib/actionSync.js',
    functions: ['commitProjectDocument', 'requestStructuralSync'],
    inputs: [{ name: 'reason', type: 'string' }],
    outputs: [{ name: 'flush', type: 'flushOutgoingProjectDocument' }],
  }),
  defineNode({
    id: 'commitProjectDocument',
    label: 'commitProjectDocument',
    layer: 'client-sync',
    component: 'Project commit gate',
    purpose: 'Validates and schedules document push after local edits.',
    why: 'Single entry for durable project JSON commits.',
    triggers: ['actionSync after mutation'],
    codeRef: 'src/lib/projectDocumentCommit.js',
    functions: ['commitProjectDocument'],
    inputs: [{ name: 'state', type: 'CanvasProjectState' }],
    outputs: [{ name: 'push', type: 'flushOutgoingProjectDocument' }],
  }),
  defineNode({
    id: 'projectSyncDocument',
    label: 'projectSyncDocument',
    layer: 'client-sync',
    component: 'Project sync document module',
    purpose: 'Reconcile, pull, push with revision CAS.',
    why: 'Implements DB-authoritative sync unless local pending.',
    triggers: ['Reconcile', 'Push after commit'],
    codeRef: 'src/lib/sync/projectSyncDocument.js',
    functions: ['reconcileActiveProject', 'flushOutgoingProjectDocument'],
    inputs: [{ name: 'expectedRevision', type: 'number' }],
    outputs: [{ name: 'revision', type: 'number' }],
  }),
  defineNode({
    id: 'projectSyncPatch',
    label: 'projectSyncPatch',
    layer: 'client-sync',
    component: 'PATCH sync ops',
    purpose: 'Builds and sends small patch ops when enabled.',
    why: 'Reduces payload size for frequent layout commits.',
    triggers: ['flushOutgoingProjectDocument when VITE_CANVAS_PATCH_SYNC'],
    codeRef: 'src/lib/sync/projectSyncPatch.js',
    functions: ['pushProjectPatchIfEnabled'],
    inputs: [{ name: 'ops', type: 'ProjectPatchOp[]' }],
    outputs: [{ name: 'PATCH response', type: 'RevisionMeta' }],
  }),
  defineNode({
    id: 'persistence',
    label: 'persistence',
    layer: 'client-sync',
    component: 'Load/save normalization',
    purpose: 'IDB read/write, card type migration, placement attach on save.',
    why: 'Cache layer must mirror server shape after reconcile.',
    triggers: ['Project load', 'saveProjectById'],
    codeRef: 'src/lib/persistence.js',
    functions: ['normalizeLoadedProject', 'buildProjectSavePayload'],
    inputs: [{ name: 'rawPayload', type: 'object' }],
    outputs: [{ name: 'state', type: 'CanvasProjectState' }],
  }),
  defineNode({
    id: 'scanFolder',
    label: 'scanFolder',
    layer: 'client-sync',
    component: 'Folder scanner',
    purpose: 'Recursively reads linked folder, groups by sync key.',
    why: 'Disk is source for folder-backed artifact discovery.',
    triggers: ['Footer Sync', 'Folder reconnect'],
    codeRef: 'src/lib/sync.js',
    functions: ['scanFolder'],
    inputs: [{ name: 'folderHandle', type: 'FileSystemDirectoryHandle' }],
    outputs: [{ name: 'filesByKey', type: 'Map<SyncKey, File[]>' }],
  }),
  defineNode({
    id: 'stageAgentChatCard',
    label: 'stageAgentChatCard',
    layer: 'client-sync',
    component: 'Agent chat dock staging',
    purpose: 'Adds agent_chat transcript cards to stagedSyncCards.',
    why: 'Agent chats default to dock until user places on canvas.',
    triggers: ['Agent chat artifact ingest pending'],
    codeRef: 'src/lib/stageAgentChatCard.js',
    inputs: [{ name: 'thread', type: 'AgentThreadIndexEntry' }],
    outputs: [{ name: 'stagedCard', type: 'StagedSyncCard' }],
  }),
  defineNode({
    id: 'loadProjectStructure',
    label: 'loadProjectStructure',
    layer: 'client-sync',
    component: 'Project boot loader',
    purpose: 'Cache-first paint then server structure fetch.',
    why: 'Fast switch UX with eventual DB convergence.',
    triggers: ['Browser refresh', 'Project switch'],
    codeRef: 'src/lib/project/loadProjectStructure.js',
    functions: ['loadProjectStructure'],
    inputs: [{ name: 'projectId', type: 'uuid' }],
    outputs: [{ name: 'payload', type: 'ProjectDocumentPayload' }],
  }),
  defineNode({
    id: 'idbProjects',
    label: 'IDB canvas-projects',
    layer: 'client-storage',
    component: 'IndexedDB project cache',
    purpose: 'Stores project document bodies for fast paint.',
    why: 'Local cache, not authority — converges to server.',
    triggers: ['Every save and reconcile pull'],
    codeRef: 'src/lib/persistence.js',
    inputs: [{ name: 'projectId', type: 'uuid' }],
    outputs: [{ name: 'payload', type: 'ProjectDocumentPayload' }],
  }),
  defineNode({
    id: 'idbFolders',
    label: 'IDB canvas-folders',
    layer: 'client-storage',
    component: 'Folder handle store',
    purpose: 'Persists FileSystemDirectoryHandle per project.',
    why: 'Browser must re-request permission; handle survives reload.',
    triggers: ['Connect folder', 'Reconnect folder'],
    codeRef: 'src/lib/persistence.js',
    inputs: [{ name: 'projectId', type: 'uuid' }],
    outputs: [{ name: 'folderHandle', type: 'FileSystemDirectoryHandle' }],
  }),
  defineNode({
    id: 'localStorageIndex',
    label: 'localStorage index',
    layer: 'client-storage',
    component: 'Workspace index',
    purpose: 'Project list, activeProjectId, connected folder names.',
    why: 'Small prefs and menu index outside IDB.',
    triggers: ['Project create/switch', 'Folder link'],
    codeRef: 'src/lib/projects.js',
    inputs: [{ name: 'index', type: 'WorkspaceIndex' }],
    outputs: [{ name: 'activeProjectId', type: 'uuid' }],
  }),
  defineNode({
    id: 'apiCanvasProjects',
    label: 'API canvas/projects',
    layer: 'api',
    component: 'Project document REST',
    purpose: 'GET/PUT/PATCH project JSON with revision CAS.',
    why: 'Server authority for rendered canvas state.',
    triggers: ['Push', 'Pull', 'Reconcile'],
    codeRef: 'server/routes/canvasProjects.js',
    functions: ['GET', 'PUT', 'PATCH'],
    inputs: [{ name: 'expectedRevision', type: 'number' }],
    outputs: [{ name: 'payload', type: 'ProjectDocumentPayload' }],
  }),
  defineNode({
    id: 'apiDiagnosticsConcentrateLayouts',
    label: 'API diagnostics concentrate layouts',
    layer: 'api',
    component: 'Concentrate layout REST',
    purpose: 'GET/PUT per-action 3D concentrate node and wire layouts.',
    why: 'Workspace-global persisted diagnostics UI prefs.',
    triggers: ['Drag end in 3D concentrate', 'Action switch hydrate'],
    codeRef: 'server/routes/diagnosticsConcentrateLayouts.js',
    functions: ['GET', 'PUT'],
    inputs: [{ name: 'specVersion', type: 'string' }],
    outputs: [{ name: 'layout', type: 'ConcentrateActionLayout' }],
  }),
  defineNode({
    id: 'apiArtifacts',
    label: 'API artifacts',
    layer: 'api',
    component: 'Primitives ingest REST',
    purpose: 'POST ingest, PATCH in-place for notes/tasks/chats.',
    why: 'Graph primitives live in Postgres, not project JSON.',
    triggers: ['createUserTask/note ingest', 'Inline save'],
    codeRef: 'server/routes/artifacts.js',
    inputs: [{ name: 'artifact', type: 'ArtifactIngestBody' }],
    outputs: [{ name: 'artifactId', type: 'uuid' }],
  }),
  defineNode({
    id: 'apiAgentChat',
    label: 'API agent/chat',
    layer: 'api',
    component: 'Agent chat completion',
    purpose: 'Routes to OpenAI or Ollama providers.',
    why: 'Server-side credential and connector routing.',
    triggers: ['Agent panel send message'],
    codeRef: 'server/routes/agent.js',
    inputs: [{ name: 'messages', type: 'ChatMessage[]' }],
    outputs: [{ name: 'reply', type: 'ChatMessage' }],
  }),
  defineNode({
    id: 'apiCanvasAgentChat',
    label: 'API canvas/agent-chat',
    layer: 'api',
    component: 'Chat session mirror',
    purpose: 'Persists thread index and session to server.',
    why: 'Cross-browser agent thread recovery.',
    triggers: ['Debounced chat mirror'],
    codeRef: 'server/routes/canvasAgentChat.js',
    inputs: [{ name: 'session', type: 'AgentChatSession' }],
    outputs: [{ name: 'threadIndex', type: 'AgentThreadIndex' }],
  }),
  defineNode({
    id: 'apiHealth',
    label: 'API health',
    layer: 'api',
    component: 'Health check',
    purpose: 'Reports dbReady and server status.',
    why: 'Boot and dev-stack readiness probe.',
    triggers: ['Dev stack start', 'Client health poll'],
    codeRef: 'server/routes/health.js',
    inputs: [],
    outputs: [{ name: 'dbReady', type: 'boolean' }],
  }),
  defineNode({
    id: 'apiClusters',
    label: 'API clusters',
    layer: 'api',
    component: 'Cluster primitives API',
    purpose: 'Cluster CRUD and graph primitives per project.',
    why: 'Graph workspace is server-side, not in project JSON.',
    triggers: ['Project open', 'Graph refresh'],
    codeRef: 'server/routes/clusters.js',
    inputs: [{ name: 'projectId', type: 'uuid' }],
    outputs: [{ name: 'primitives', type: 'PrimitiveGraph' }],
  }),
  defineNode({
    id: 'apiSpec',
    label: 'API spec',
    layer: 'api',
    component: 'Spec canvas dual-write',
    purpose: 'Mirrors layout/viewport to spec_canvas_state.',
    why: 'Secondary projection until spec cutover.',
    triggers: ['Successful document push'],
    codeRef: 'server/routes/spec.js',
    inputs: [{ name: 'layout', type: 'SpecCanvasLayout' }],
    outputs: [{ name: 'specRevision', type: 'number' }],
  }),
  defineNode({
    id: 'apiFlows',
    label: 'API flows',
    layer: 'api',
    component: 'Exploration REST',
    purpose: 'Flow document CRUD and SSE stream.',
    why: 'Flows are revisioned separately from canvas layout.',
    triggers: ['Create/open flow card'],
    codeRef: 'server/routes/flows.js',
    inputs: [{ name: 'flowDocument', type: 'FlowDocument' }],
    outputs: [{ name: 'flowId', type: 'uuid' }],
  }),
  defineNode({
    id: 'apiLiveArtifacts',
    label: 'API live-artifacts',
    layer: 'api',
    component: 'Live artifact REST',
    purpose: 'Scheduled live sources and project updates.',
    why: 'Live cards poll external sources independently.',
    triggers: ['Create live card', 'Live worker run'],
    codeRef: 'server/routes/liveArtifacts.js',
    inputs: [{ name: 'liveArtifact', type: 'LiveArtifact' }],
    outputs: [{ name: 'projectUpdate', type: 'ProjectUpdateEvent' }],
  }),
  defineNode({
    id: 'apiAgents',
    label: 'API agents',
    layer: 'api',
    component: 'Agent artifact v5 REST',
    purpose: 'CRUD and POST /api/agents/:id/execute for image agents.',
    why: 'Structured agent cards with execution history and transformer routing.',
    triggers: ['Run agent from canvas'],
    codeRef: 'server/routes/agents.js',
    inputs: [{ name: 'agentId', type: 'uuid' }],
    outputs: [{ name: 'execution', type: 'Execution' }],
  }),
  defineNode({
    id: 'agentExecutionRunner',
    label: 'agentExecutionRunner',
    layer: 'api',
    component: 'Agent execution orchestrator',
    purpose: 'Creates execution rows, relates inputs, invokes image transformer.',
    why: 'Server-side run lifecycle with provenance and generated artifact inserts.',
    triggers: ['POST /api/agents/:id/execute'],
    codeRef: 'server/services/agentExecutionRunner.js',
    inputs: [{ name: 'promptNoteArtifactId', type: 'uuid' }],
    outputs: [{ name: 'execution', type: 'Execution' }],
  }),
  defineNode({
    id: 'imageTransformer',
    label: 'imageTransformer',
    layer: 'api',
    component: 'Image generation transformer',
    purpose: 'Routes OpenAI, Gemini, or local image generation providers.',
    why: 'Bounded transformer invoked by agent executions for image outputs.',
    triggers: ['Agent execution with transformer_image_generation'],
    codeRef: 'server/services/imageTransformer.js',
    inputs: [{ name: 'prompt', type: 'string' }],
    outputs: [{ name: 'images', type: 'GeneratedImage[]' }],
  }),
  defineNode({
    id: 'apiMusic',
    label: 'API music',
    layer: 'api',
    component: 'Music framework REST',
    purpose: 'Beat agents, transport, sonic sketches.',
    why: 'Music cards have separate kernel and server state.',
    triggers: ['Create beat agent'],
    codeRef: 'server/routes/music.js',
    inputs: [{ name: 'musicAgent', type: 'MusicAgent' }],
    outputs: [{ name: 'transport', type: 'MusicTransport' }],
  }),
  defineNode({
    id: 'apiStudios',
    label: 'API studios',
    layer: 'api',
    component: 'Nested studio REST',
    purpose: 'Studio CRUD, overview, invoke-child, archive/restore, surfaces, promotions.',
    why: 'Studios are server-backed composite artifacts with flow-linked child projection.',
    triggers: ['Create studio', 'Invoke child', 'Archive/restore child'],
    codeRef: 'server/routes/studios.js',
    inputs: [{ name: 'studioInput', type: 'StudioMutationBody' }],
    outputs: [{ name: 'overview', type: 'StudioOverview' }],
  }),
  defineNode({
    id: 'apiAgentTemplates',
    label: 'API agent/templates',
    layer: 'api',
    component: 'Agent template REST',
    purpose: 'Multi-file agent template CRUD and import from master files.',
    why: 'Database-backed agent definitions separate from chat connectors.',
    triggers: ['Template admin', 'Import master files'],
    codeRef: 'server/routes/agentTemplates.js',
    inputs: [{ name: 'template', type: 'AgentTemplateBody' }],
    outputs: [{ name: 'templateId', type: 'uuid' }],
  }),
  defineNode({
    id: 'apiCanvasPreviews',
    label: 'API canvas/previews',
    layer: 'api',
    component: 'Preview blob REST',
    purpose: 'Stores and serves preview bytes for cards.',
    why: 'Keeps heavy preview data out of project JSON.',
    triggers: ['Preview hydration', 'Card preview save'],
    codeRef: 'server/routes/canvasPreviews.js',
    inputs: [{ name: 'cacheKey', type: 'string' }],
    outputs: [{ name: 'blob', type: 'PreviewBlob' }],
  }),
  defineNode({
    id: 'apiPrimitives',
    label: 'API primitives',
    layer: 'api',
    component: 'Graph primitives REST',
    purpose: 'Lists cluster primitives and relationship mutations.',
    why: 'Workspace tree and graph inspector read unified primitives.',
    triggers: ['Workspace tree open', 'Graph refresh'],
    codeRef: 'server/routes/primitives.js',
    inputs: [{ name: 'clusterId', type: 'uuid' }],
    outputs: [{ name: 'primitives', type: 'PrimitiveGraph' }],
  }),
  defineNode({
    id: 'apiAgentTypes',
    label: 'API agent/types',
    layer: 'api',
    component: 'Agent type catalog REST',
    purpose: 'Registers agent card type metadata and capabilities.',
    why: 'Structured agent cards reference typed definitions.',
    triggers: ['Create agent card'],
    codeRef: 'server/routes/agentTypes.js',
    inputs: [{ name: 'agentType', type: 'AgentTypeBody' }],
    outputs: [{ name: 'typeId', type: 'string' }],
  }),
  defineNode({
    id: 'apiStateMachines',
    label: 'API state-machines',
    layer: 'api',
    component: 'State machine REST',
    purpose: 'CRUD for state machine artifact documents.',
    why: 'Live and agent cards may embed state machine definitions.',
    triggers: ['Create state machine artifact'],
    codeRef: 'server/routes/stateMachines.js',
    inputs: [{ name: 'machine', type: 'StateMachineBody' }],
    outputs: [{ name: 'machineId', type: 'uuid' }],
  }),
  defineNode({
    id: 'dbCanvasProjectDocument',
    label: 'canvas_project_document',
    layer: 'postgres',
    component: 'Project document table',
    purpose: 'Authoritative project JSON payload + revision.',
    why: 'Rendered canvas authority until spec cutover.',
    triggers: ['Every successful PUT/PATCH'],
    codeRef: 'server/migrations/0005_canvas_projects.sql',
    inputs: [{ name: 'payload', type: 'jsonb' }],
    outputs: [{ name: 'revision', type: 'integer' }],
  }),
  defineNode({
    id: 'dbSpecCanvasState',
    label: 'spec_canvas_state',
    layer: 'postgres',
    component: 'Spec layout projection',
    purpose: 'Layout/viewport dual-write target.',
    why: 'Diagnostic projection for future spec authority.',
    triggers: ['Post-push dual-write'],
    codeRef: 'server/migrations/0010_spec_data_plane.sql',
    inputs: [{ name: 'viewport', type: 'jsonb' }],
    outputs: [{ name: 'version', type: 'integer' }],
  }),
  defineNode({
    id: 'dbDiagnosticsConcentrateLayout',
    label: 'diagnostics_concentrate_layout',
    layer: 'postgres',
    component: 'Concentrate layout table',
    purpose: 'Per-action 3D concentrate node overrides and edge anchors.',
    why: 'Restore user-arranged action graphs across sessions.',
    triggers: ['PUT concentrate layout'],
    codeRef: 'server/migrations/0023_diagnostics_concentrate_layouts.sql',
    inputs: [{ name: 'node_overrides', type: 'jsonb' }, { name: 'edge_anchors', type: 'jsonb' }],
    outputs: [{ name: 'updated_at', type: 'timestamptz' }],
  }),
  defineNode({
    id: 'dbArtifact',
    label: 'artifact',
    layer: 'postgres',
    component: 'Primitives artifact table',
    purpose: 'Hash-deduped ingested file records.',
    why: 'Graph primitives reference artifact rows.',
    triggers: ['POST /artifacts/ingest'],
    codeRef: 'server/migrations/0001_initial.sql',
    inputs: [{ name: 'content_hash', type: 'text' }],
    outputs: [{ name: 'id', type: 'uuid' }],
  }),
  defineNode({
    id: 'dbAgentChat',
    label: 'agent chat tables',
    layer: 'postgres',
    component: 'Chat session storage',
    purpose: 'canvas_agent_chat_session and thread index.',
    why: 'Server mirror of agent conversations.',
    triggers: ['PUT /canvas/agent-chat'],
    codeRef: 'server/migrations/0001_initial.sql',
    inputs: [{ name: 'session', type: 'jsonb' }],
    outputs: [{ name: 'thread_id', type: 'uuid' }],
  }),
  defineNode({
    id: 'dbStudio',
    label: 'studio tables',
    layer: 'postgres',
    component: 'Nested studio storage',
    purpose: 'studio, studio_surface, context packets, steps, candidates, promotions.',
    why: 'Studios persist separately from canvas project JSON.',
    triggers: ['POST /studios', 'invoke-child', 'archive/restore'],
    codeRef: 'server/repositories/studios.js',
    inputs: [{ name: 'studioRow', type: 'StudioRecord' }],
    outputs: [{ name: 'studioId', type: 'uuid' }],
  }),
  defineNode({
    id: 'dbFlowDocument',
    label: 'flow_document',
    layer: 'postgres',
    component: 'Exploration document tables',
    purpose: 'flow_document, flow_node, flow_edge with revision CAS.',
    why: 'Explorations are revisioned independently from canvas layout.',
    triggers: ['PUT /flows/:id', 'archive child removes parent node'],
    codeRef: 'server/repositories/flows.js',
    inputs: [{ name: 'flowSnapshot', type: 'FlowDocumentPayload' }],
    outputs: [{ name: 'revision', type: 'integer' }],
  }),
  defineNode({
    id: 'dbAgentTemplate',
    label: 'agent_template',
    layer: 'postgres',
    component: 'Agent template storage',
    purpose: 'agent_template and agent_template_file rows with revision CAS.',
    why: 'Multi-file agent definitions live in Postgres.',
    triggers: ['PUT /agent/templates/:id'],
    codeRef: 'server/routes/agentTemplates.js',
    inputs: [{ name: 'template', type: 'AgentTemplateRecord' }],
    outputs: [{ name: 'revision', type: 'integer' }],
  }),
  defineNode({
    id: 'dbAgentExecution',
    label: 'agent execution tables',
    layer: 'postgres',
    component: 'Agent artifact and execution storage',
    purpose: 'agent_artifact, execution, and generated image artifact rows.',
    why: 'Image agent runs persist provenance and outputs in Postgres.',
    triggers: ['POST /api/agents/:id/execute'],
    codeRef: 'server/migrations/0016_agent_system.sql',
    inputs: [{ name: 'execution', type: 'ExecutionRecord' }],
    outputs: [{ name: 'artifactIds', type: 'uuid[]' }],
  }),
  defineNode({
    id: 'userFolder',
    label: 'User folder',
    layer: 'external',
    component: 'Linked project directory',
    purpose: 'Stores notes__, tasks__, agent-chat, and generated image files on disk.',
    why: 'Folder-backed artifacts sync bidirectionally with canvas.',
    triggers: ['Save note/task', 'Folder scan', 'Agent transcript write', 'Image agent output write'],
    codeRef: 'src/lib/folderWrite.js',
    inputs: [{ name: 'fileBytes', type: 'Uint8Array' }],
    outputs: [{ name: 'files', type: 'File[]' }],
  }),
  defineNode({
    id: 'ollama',
    label: 'Ollama',
    layer: 'external',
    component: 'Local LLM provider',
    purpose: 'Gemma and other models at localhost:11434.',
    why: 'Offline-capable agent chat without API keys.',
    triggers: ['Agent chat with Ollama connector'],
    codeRef: 'server/services/ollamaChat.js',
    inputs: [{ name: 'prompt', type: 'ChatMessage[]' }],
    outputs: [{ name: 'completion', type: 'string' }],
  }),
  defineNode({
    id: 'openai',
    label: 'OpenAI',
    layer: 'external',
    component: 'Cloud LLM provider',
    purpose: 'GPT chat completions via stored credential.',
    why: 'Default cloud agent chat provider.',
    triggers: ['Agent chat with OpenAI connector'],
    codeRef: 'server/services/openaiChat.js',
    inputs: [{ name: 'prompt', type: 'ChatMessage[]' }],
    outputs: [{ name: 'completion', type: 'string' }],
  }),
  defineNode({
    id: 'openaiImage',
    label: 'OpenAI Images',
    layer: 'external',
    component: 'OpenAI image API',
    purpose: 'GPT Image and DALL·E generation via stored credential.',
    why: 'Cloud image agent provider for OpenAI transformer settings.',
    triggers: ['Image agent with provider openai'],
    codeRef: 'server/services/imageTransformer.js',
    inputs: [{ name: 'prompt', type: 'string' }],
    outputs: [{ name: 'images', type: 'GeneratedImage[]' }],
  }),
  defineNode({
    id: 'gemini',
    label: 'Gemini',
    layer: 'external',
    component: 'Google Gemini image API',
    purpose: 'Gemini image models via GEMINI_API_KEY or stored credential.',
    why: 'Cloud image agent provider for Gemini transformer settings.',
    triggers: ['Image agent with provider gemini'],
    codeRef: 'server/services/imageTransformer.js',
    inputs: [{ name: 'prompt', type: 'string' }],
    outputs: [{ name: 'images', type: 'GeneratedImage[]' }],
  }),
];

export const ARCHITECTURE_GRAPH_PIPES = [
  definePipe({
    id: 'pipe-addMenu-newTaskDialog',
    source: 'addMenu',
    target: 'newTaskDialog',
    pipeLabel: 'open dialog',
    dataFlow: 'User selection Add task → opens NewTaskDialog with placement coords.',
    payloadTypes: ['CreateDialogRequest'],
    trigger: 'Add menu item click when folder linked.',
    why: 'Tasks require modal input before file write.',
  }),
  definePipe({
    id: 'pipe-newTaskDialog-useCanvasDocument',
    source: 'newTaskDialog',
    target: 'useCanvasDocument',
    pipeLabel: 'save payload',
    dataFlow: 'Form values: prefix, name, body, taskStatus, position.',
    payloadTypes: ['NewTaskSavePayload'],
    trigger: 'User confirms New Task dialog.',
    why: 'Central hook owns canvas state mutations.',
  }),
  definePipe({
    id: 'pipe-useCanvasDocument-createUserTask',
    source: 'useCanvasDocument',
    target: 'createUserTask',
    pipeLabel: 'createUserTaskArtifact',
    dataFlow: 'Project id, folder handle, task fields, cluster context.',
    payloadTypes: ['CreateUserTaskInput'],
    trigger: 'handleSaveNewTask after folder permission check.',
    why: 'Ingest module writes file and builds card.',
    functions: ['createUserTaskArtifact'],
  }),
  definePipe({
    id: 'pipe-createUserTask-userFolder',
    source: 'createUserTask',
    target: 'userFolder',
    pipeLabel: 'tasks__*.md',
    dataFlow: 'YAML frontmatter taskStatus + markdown body written to disk.',
    payloadTypes: ['UserTaskFile', 'tasks__{name}-v1.md'],
    trigger: 'createUserTaskArtifact folder write phase.',
    why: 'Tasks are folder-backed like notes.',
  }),
  definePipe({
    id: 'pipe-createUserTask-artifactPlacementsMap',
    source: 'createUserTask',
    target: 'artifactPlacementsMap',
    pipeLabel: 'new card + placement',
    dataFlow: 'New CanvasCard appended; placement map entry surface=canvas.',
    payloadTypes: ['CanvasCard', 'ArtifactPlacementEntry v2'],
    trigger: 'After card built, before IDB save.',
    why: 'Placement SSOT recorded on every structural add.',
  }),
  definePipe({
    id: 'pipe-createUserTask-apiArtifacts',
    source: 'createUserTask',
    target: 'apiArtifacts',
    pipeLabel: 'POST ingest',
    dataFlow: 'Artifact ingest body with canvas_kind user_task.',
    payloadTypes: ['ArtifactIngestBody'],
    trigger: 'Primitive ingest after file write.',
    why: 'Graph primitives live in Postgres.',
  }),
  definePipe({
    id: 'pipe-apiArtifacts-dbArtifact',
    source: 'apiArtifacts',
    target: 'dbArtifact',
    pipeLabel: 'UPSERT artifact',
    dataFlow: 'Content hash dedupe, type user_task, URI optional.',
    payloadTypes: ['artifact row'],
    trigger: 'Successful ingest handler.',
    why: 'Durable primitive storage.',
  }),
  definePipe({
    id: 'pipe-useCanvasDocument-idbProjects',
    source: 'useCanvasDocument',
    target: 'idbProjects',
    pipeLabel: 'saveProjectById',
    dataFlow: 'Full project state with new card and placement map.',
    payloadTypes: ['ProjectDocumentPayload'],
    trigger: 'After local card append.',
    why: 'Cache updated before remote push.',
  }),
  definePipe({
    id: 'pipe-useCanvasDocument-actionSync',
    source: 'useCanvasDocument',
    target: 'actionSync',
    pipeLabel: 'requestStructuralSync',
    dataFlow: 'Structural change reason; awaits local save.',
    payloadTypes: ['SyncReason'],
    trigger: 'After note/task create completes.',
    why: 'Triggers push pipeline.',
  }),
  definePipe({
    id: 'pipe-actionSync-commitProjectDocument',
    source: 'actionSync',
    target: 'commitProjectDocument',
    pipeLabel: 'commit',
    dataFlow: 'Project state, staged cards, pushRemote flag.',
    payloadTypes: ['CommitProjectDocumentInput'],
    trigger: 'Structural or layout commit.',
    why: 'Single commit gate before push.',
  }),
  definePipe({
    id: 'pipe-commitProjectDocument-projectSyncDocument',
    source: 'commitProjectDocument',
    target: 'projectSyncDocument',
    pipeLabel: 'flushOutgoing',
    dataFlow: 'Payload + expectedRevision for CAS.',
    payloadTypes: ['ProjectDocumentPayload', 'expectedRevision'],
    trigger: 'commitProjectDocument when server sync enabled.',
    why: 'Implements revision-aware push.',
    functions: ['flushOutgoingProjectDocument'],
  }),
  definePipe({
    id: 'pipe-projectSyncDocument-projectSyncPatch',
    source: 'projectSyncDocument',
    target: 'projectSyncPatch',
    pipeLabel: 'PATCH ops',
    dataFlow: 'Small patch ops when diff below threshold.',
    payloadTypes: ['ProjectPatchOp[]'],
    trigger: 'VITE_CANVAS_PATCH_SYNC enabled and ops small.',
    why: 'Efficient layout commits.',
  }),
  definePipe({
    id: 'pipe-projectSyncPatch-apiCanvasProjects',
    source: 'projectSyncPatch',
    target: 'apiCanvasProjects',
    pipeLabel: 'PATCH /canvas/projects/:id',
    dataFlow: 'ops, expectedRevision, clientId, traceId.',
    payloadTypes: ['PatchProjectBody'],
    trigger: 'PATCH path selected by flush.',
    why: 'Server applies incremental ops.',
  }),
  definePipe({
    id: 'pipe-projectSyncDocument-apiCanvasProjects',
    source: 'projectSyncDocument',
    target: 'apiCanvasProjects',
    pipeLabel: 'PUT fallback',
    dataFlow: 'Full payload PUT when PATCH unavailable or conflict.',
    payloadTypes: ['ProjectDocumentPayload'],
    trigger: 'PATCH disabled or large diff.',
    why: 'Full document fallback path.',
  }),
  definePipe({
    id: 'pipe-apiCanvasProjects-dbCanvasProjectDocument',
    source: 'apiCanvasProjects',
    target: 'dbCanvasProjectDocument',
    pipeLabel: 'jsonb payload',
    dataFlow: 'Revision increment with CAS on expectedRevision.',
    payloadTypes: ['canvas_project_document row'],
    trigger: 'Successful PUT/PATCH handler.',
    why: 'Server authority row updated.',
  }),
  definePipe({
    id: 'pipe-apiCanvasProjects-apiSpec',
    source: 'apiCanvasProjects',
    target: 'apiSpec',
    pipeLabel: 'dual-write',
    dataFlow: 'Layout/viewport extracted to spec_canvas_state.',
    payloadTypes: ['SpecCanvasLayout'],
    trigger: 'After successful document CAS.',
    why: 'Spec projection maintained on save.',
  }),
  definePipe({
    id: 'pipe-apiSpec-dbSpecCanvasState',
    source: 'apiSpec',
    target: 'dbSpecCanvasState',
    pipeLabel: 'spec row',
    dataFlow: 'Viewport and card positions projection.',
    payloadTypes: ['spec_canvas_state row'],
    trigger: 'syncSpecCanvasStateFromPayload.',
    why: 'Secondary diagnostic table.',
  }),
  definePipe({
    id: 'pipe-apiDiagnosticsConcentrateLayouts-dbDiagnosticsConcentrateLayout',
    source: 'apiDiagnosticsConcentrateLayouts',
    target: 'dbDiagnosticsConcentrateLayout',
    pipeLabel: 'upsert layout',
    dataFlow: 'node_overrides and edge_anchors keyed by action_id + spec_version.',
    payloadTypes: ['diagnostics_concentrate_layout row'],
    trigger: 'PUT /canvas/diagnostics/concentrate-layouts/:actionId.',
    why: 'Persist concentrate mode arrangement.',
  }),
  definePipe({
    id: 'pipe-addMenu-newNoteDialog',
    source: 'addMenu',
    target: 'newNoteDialog',
    pipeLabel: 'open dialog',
    dataFlow: 'Add note selection with optional placement.',
    payloadTypes: ['CreateDialogRequest'],
    trigger: 'Add menu → Add note.',
    why: 'Notes need modal before write.',
  }),
  definePipe({
    id: 'pipe-newNoteDialog-useCanvasDocument',
    source: 'newNoteDialog',
    target: 'useCanvasDocument',
    pipeLabel: 'save payload',
    dataFlow: 'prefix, name, body, linkTargetRefs, position.',
    payloadTypes: ['NewNoteSavePayload'],
    trigger: 'Note dialog confirm.',
    why: 'Hook handles save pipeline.',
  }),
  definePipe({
    id: 'pipe-useCanvasDocument-createUserNote',
    source: 'useCanvasDocument',
    target: 'createUserNote',
    pipeLabel: 'createUserNoteArtifact',
    dataFlow: 'Note fields and folder handle.',
    payloadTypes: ['CreateUserNoteInput'],
    trigger: 'handleSaveNewNote.',
    why: 'Parallel to task ingest.',
  }),
  definePipe({
    id: 'pipe-createUserNote-userFolder',
    source: 'createUserNote',
    target: 'userFolder',
    pipeLabel: 'notes__*.md',
    dataFlow: 'Markdown note file at project folder root.',
    payloadTypes: ['UserNoteFile', 'notes__{name}-v1.md'],
    trigger: 'Folder write in createUserNote.',
    why: 'Notes are folder-backed.',
  }),
  definePipe({
    id: 'pipe-canvasChrome-scanFolder',
    source: 'canvasChrome',
    target: 'scanFolder',
    pipeLabel: 'Footer Sync',
    dataFlow: 'folderHandle from IDB; recursive directory read.',
    payloadTypes: ['FolderScanRequest'],
    trigger: 'User clicks Sync in footer.',
    why: 'Disk discovery starts sync flow.',
  }),
  definePipe({
    id: 'pipe-scanFolder-syncStaging',
    source: 'scanFolder',
    target: 'syncStaging',
    pipeLabel: 'filesByKey',
    dataFlow: 'Grouped files matched to canvas and dock keys.',
    payloadTypes: ['Map<SyncKey, File[]>'],
    trigger: 'scanFolder completion.',
    why: 'Staging computes diff vs project state.',
    functions: ['buildSyncChangesFromFolder'],
  }),
  definePipe({
    id: 'pipe-syncStaging-syncConfirm',
    source: 'syncStaging',
    target: 'syncConfirm',
    pipeLabel: 'confirm changes',
    dataFlow: 'List of new/changed files needing user OK.',
    payloadTypes: ['SyncChange[]'],
    trigger: 'Non-agent new disk files detected.',
    why: 'User must approve unexpected ingest.',
  }),
  definePipe({
    id: 'pipe-syncStaging-artifactPlacement',
    source: 'syncStaging',
    target: 'artifactPlacement',
    pipeLabel: 'heal placement',
    dataFlow: 'Staged rows and duplicate resolution.',
    payloadTypes: ['StagedSyncCard[]'],
    trigger: 'After scan applies or auto-stages agent_chat.',
    why: 'Maintains canvas XOR dock invariant.',
  }),
  definePipe({
    id: 'pipe-syncStaging-stageAgentChatCard',
    source: 'syncStaging',
    target: 'stageAgentChatCard',
    pipeLabel: 'auto-stage chat',
    dataFlow: 'agent_chat files silently added to dock.',
    payloadTypes: ['AgentChatFile'],
    trigger: 'Folder scan finds agent_chat without confirm.',
    why: 'Agent chats skip SYNC dialog.',
  }),
  definePipe({
    id: 'pipe-loadProjectStructure-idbProjects',
    source: 'loadProjectStructure',
    target: 'idbProjects',
    pipeLabel: 'cache-first read',
    dataFlow: 'Paint from IDB before server round-trip.',
    payloadTypes: ['ProjectDocumentPayload'],
    trigger: 'Browser refresh or project switch boot.',
    why: 'Fast initial paint.',
  }),
  definePipe({
    id: 'pipe-loadProjectStructure-persistence',
    source: 'loadProjectStructure',
    target: 'persistence',
    pipeLabel: 'normalize',
    dataFlow: 'Raw payload → user_task/user_note migration, placement reconcile.',
    payloadTypes: ['ProjectDocumentPayload'],
    trigger: 'After IDB or server fetch.',
    why: 'Load fence normalizes legacy shapes.',
    functions: ['normalizeLoadedProject'],
  }),
  definePipe({
    id: 'pipe-loadProjectStructure-useProjectSyncLifecycle',
    source: 'loadProjectStructure',
    target: 'useProjectSyncLifecycle',
    pipeLabel: 'reconcile',
    dataFlow: 'Triggers reconcileActiveProject when no pending local edit.',
    payloadTypes: ['ReconcileRequest'],
    trigger: 'Post-load background reconcile.',
    why: 'Converge cache to DB authority.',
  }),
  definePipe({
    id: 'pipe-useProjectSyncLifecycle-projectSyncDocument',
    source: 'useProjectSyncLifecycle',
    target: 'projectSyncDocument',
    pipeLabel: 'reconcileActiveProject',
    dataFlow: 'Compare local revision vs server; pull or push.',
    payloadTypes: ['ReconcileInput'],
    trigger: 'Visibility resume, switch, manual refresh.',
    why: 'Core DB authority logic.',
    functions: ['reconcileActiveProject'],
  }),
  definePipe({
    id: 'pipe-projectSyncDocument-apiCanvasProjects-reconcile',
    source: 'projectSyncDocument',
    target: 'apiCanvasProjects',
    pipeLabel: 'GET/PUT pull',
    dataFlow: 'Fetch server document or push if local newer.',
    payloadTypes: ['RevisionMeta', 'ProjectDocumentPayload'],
    trigger: 'Reconcile mismatch.',
    why: 'Server is authority unless pending local.',
  }),
  definePipe({
    id: 'pipe-syncHoldingTray-artifactPlacement',
    source: 'syncHoldingTray',
    target: 'artifactPlacement',
    pipeLabel: 'moveToCanvas',
    dataFlow: 'Staged card dropped on canvas with x,y.',
    payloadTypes: ['StagedSyncCard', 'CanvasPosition'],
    trigger: 'User drags from dock to canvas.',
    why: 'Transfers surface from dock to canvas.',
    functions: ['moveToCanvas', 'placeStagedCardOnCanvas'],
  }),
  definePipe({
    id: 'pipe-artifactPlacement-artifactPlacementsMap',
    source: 'artifactPlacement',
    target: 'artifactPlacementsMap',
    pipeLabel: 'update map',
    dataFlow: 'Canonical key → surface canvas, slim placement ref.',
    payloadTypes: ['ArtifactPlacementsMap'],
    trigger: 'Any placement move.',
    why: 'Persist placement SSOT.',
  }),
  definePipe({
    id: 'pipe-artifactPlacement-useActionSync',
    source: 'artifactPlacement',
    target: 'useActionSync',
    pipeLabel: 'placement sync',
    dataFlow: 'requestPlacementSync after dock/canvas transfer.',
    payloadTypes: ['PlacementSyncReason'],
    trigger: 'After successful move.',
    why: 'Push placement change to server.',
  }),
  definePipe({
    id: 'pipe-canvas-useActionSync',
    source: 'canvas',
    target: 'useActionSync',
    pipeLabel: 'layout commit',
    dataFlow: 'Card positions and canvasView after drag end.',
    payloadTypes: ['LayoutCommitPayload'],
    trigger: 'Pointer-up after card or cluster drag.',
    why: 'Layout changes debounced to push.',
    functions: ['handleInteractionCommit'],
  }),
  definePipe({
    id: 'pipe-projectSyncDocument-idbProjects',
    source: 'projectSyncDocument',
    target: 'idbProjects',
    pipeLabel: 'cache update',
    dataFlow: 'Pulled server payload written to IDB.',
    payloadTypes: ['ProjectDocumentPayload'],
    trigger: 'Server wins reconcile or after push ack.',
    why: 'Cache converges to DB truth.',
  }),
  definePipe({
    id: 'pipe-agentPanel-apiAgentChat',
    source: 'agentPanel',
    target: 'apiAgentChat',
    pipeLabel: 'POST /agent/chat',
    dataFlow: 'Connector id, messages, optional images.',
    payloadTypes: ['AgentChatRequest'],
    trigger: 'User sends chat message.',
    why: 'Server routes to LLM provider.',
  }),
  definePipe({
    id: 'pipe-apiAgentChat-ollama',
    source: 'apiAgentChat',
    target: 'ollama',
    pipeLabel: 'Ollama completion',
    dataFlow: 'Chat messages to local model endpoint.',
    payloadTypes: ['OllamaChatRequest'],
    trigger: 'Ollama connector selected.',
    why: 'Local inference path.',
  }),
  definePipe({
    id: 'pipe-apiAgentChat-openai',
    source: 'apiAgentChat',
    target: 'openai',
    pipeLabel: 'OpenAI completion',
    dataFlow: 'Chat messages with API credential.',
    payloadTypes: ['OpenAIChatRequest'],
    trigger: 'OpenAI connector selected.',
    why: 'Cloud inference path.',
  }),
  definePipe({
    id: 'pipe-apiAgentChat-userFolder',
    source: 'apiAgentChat',
    target: 'userFolder',
    pipeLabel: 'transcript file',
    dataFlow: 'notes__agent-chat-*.md transcript append.',
    payloadTypes: ['AgentChatTranscriptFile'],
    trigger: 'After completion; client writes folder file.',
    why: 'Folder-backed chat history.',
  }),
  definePipe({
    id: 'pipe-apiAgentChat-stageAgentChatCard',
    source: 'apiAgentChat',
    target: 'stageAgentChatCard',
    pipeLabel: 'stage to dock',
    dataFlow: 'New or updated agent_chat staged card.',
    payloadTypes: ['StagedSyncCard'],
    trigger: 'Transcript ingest pending placement.',
    why: 'Default agent chat location is dock.',
  }),
  definePipe({
    id: 'pipe-stageAgentChatCard-syncHoldingTray',
    source: 'stageAgentChatCard',
    target: 'syncHoldingTray',
    pipeLabel: 'dock UI',
    dataFlow: 'Staged card appears in holding tray.',
    payloadTypes: ['StagedSyncCard[]'],
    trigger: 'After stageAgentChatCard.',
    why: 'User sees chat in dock until placed.',
  }),
  definePipe({
    id: 'pipe-apiAgentChat-apiCanvasAgentChat',
    source: 'apiAgentChat',
    target: 'apiCanvasAgentChat',
    pipeLabel: 'mirror session',
    dataFlow: 'Debounced session + thread index PUT.',
    payloadTypes: ['AgentChatSession'],
    trigger: 'Chat mirror debounce.',
    why: 'Cross-tab session recovery.',
  }),
  definePipe({
    id: 'pipe-apiCanvasAgentChat-dbAgentChat',
    source: 'apiCanvasAgentChat',
    target: 'dbAgentChat',
    pipeLabel: 'persist session',
    dataFlow: 'Thread index and session JSON.',
    payloadTypes: ['canvas_agent_chat_session row'],
    trigger: 'Successful mirror PUT.',
    why: 'Server-side chat backup.',
  }),
  definePipe({
    id: 'pipe-persistence-artifactPlacementsMap',
    source: 'persistence',
    target: 'artifactPlacementsMap',
    pipeLabel: 'attach on save',
    dataFlow: 'Build placement map from cards + staged.',
    payloadTypes: ['ArtifactPlacementsMap'],
    trigger: 'buildProjectSavePayload.',
    why: 'Every save includes placement SSOT.',
  }),
  definePipe({
    id: 'pipe-idbFolders-scanFolder',
    source: 'idbFolders',
    target: 'scanFolder',
    pipeLabel: 'folder handle',
    dataFlow: 'Restored FileSystemDirectoryHandle for scan.',
    payloadTypes: ['FileSystemDirectoryHandle'],
    trigger: 'Footer Sync when folder linked.',
    why: 'Scan needs live folder permission.',
  }),
  definePipe({
    id: 'pipe-addMenu-createStudioDialog',
    source: 'addMenu',
    target: 'createStudioDialog',
    pipeLabel: 'open dialog',
    dataFlow: 'User selects Add studio from menu.',
    payloadTypes: ['CreateDialogRequest'],
    trigger: 'Add menu item click.',
    why: 'Studio creation requires title and playbook selection.',
  }),
  definePipe({
    id: 'pipe-addMenu-createSonicStudioDialog',
    source: 'addMenu',
    target: 'createSonicStudioDialog',
    pipeLabel: 'open dialog',
    dataFlow: 'User selects Add Sonic Studio from menu.',
    payloadTypes: ['CreateDialogRequest'],
    trigger: 'Add menu item click when project active.',
    why: 'Sonic Studio creation requires a name before card append.',
  }),
  definePipe({
    id: 'pipe-createSonicStudioDialog-useCanvasDocument',
    source: 'createSonicStudioDialog',
    target: 'useCanvasDocument',
    pipeLabel: 'create sonic card',
    dataFlow: 'createSonicStudioRecord then append sonic_studio card to project JSON.',
    payloadTypes: ['CreateSonicStudioInput', 'SonicStudioCard'],
    trigger: 'User confirms Create Sonic Studio dialog.',
    why: 'Canvas document hook owns card placement and sync.',
  }),
  definePipe({
    id: 'pipe-createStudioDialog-useCanvasDocument',
    source: 'createStudioDialog',
    target: 'useCanvasDocument',
    pipeLabel: 'create studio card',
    dataFlow: 'POST /studios then append studio card to project JSON.',
    payloadTypes: ['CreateStudioInput', 'StudioOverview'],
    trigger: 'User confirms Create Studio dialog.',
    why: 'Canvas document hook owns card placement.',
  }),
  definePipe({
    id: 'pipe-useCanvasDocument-apiStudios-create',
    source: 'useCanvasDocument',
    target: 'apiStudios',
    pipeLabel: 'POST /studios',
    dataFlow: 'Creates studio artifact, primary surface, and overview payload.',
    payloadTypes: ['CreateStudioBody'],
    trigger: 'handleSaveNewStudio after dialog submit.',
    why: 'Studios are server-created composite artifacts.',
  }),
  definePipe({
    id: 'pipe-apiStudios-dbStudio',
    source: 'apiStudios',
    target: 'dbStudio',
    pipeLabel: 'persist studio',
    dataFlow: 'Inserts studio, artifact, surface, and playbook rows.',
    payloadTypes: ['StudioRecord', 'StudioSurfaceRecord'],
    trigger: 'Successful studio route handler.',
    why: 'Authoritative studio state lives in Postgres.',
  }),
  definePipe({
    id: 'pipe-canvas-studioDashboard',
    source: 'canvas',
    target: 'studioDashboard',
    pipeLabel: 'open studio',
    dataFlow: 'Studio card opens embedded StudioDashboard in card modal.',
    payloadTypes: ['StudioCard', 'StudioOverview'],
    trigger: 'User opens studio card.',
    why: 'Studios edit in dedicated dashboard UI.',
  }),
  definePipe({
    id: 'pipe-studioDashboard-flowEditor',
    source: 'studioDashboard',
    target: 'flowEditor',
    pipeLabel: 'open primary surface',
    dataFlow: 'Sets active surface to primary Exploration flow card.',
    payloadTypes: ['StudioSurfaceRef'],
    trigger: 'Open primary Exploration from dashboard.',
    why: 'Domain studios explore via flow editor.',
  }),
  definePipe({
    id: 'pipe-studioDashboard-apiStudios',
    source: 'studioDashboard',
    target: 'apiStudios',
    pipeLabel: 'overview / restore',
    dataFlow: 'GET overview, POST restore/archive, list archived children.',
    payloadTypes: ['StudioOverview', 'RestoreStudioBody'],
    trigger: 'Dashboard refresh, archive, or restore child.',
    why: 'Dashboard reads and mutates studio server state.',
  }),
  definePipe({
    id: 'pipe-flowEditor-apiStudios',
    source: 'flowEditor',
    target: 'apiStudios',
    pipeLabel: 'invoke child',
    dataFlow: 'Selection payload → POST /studios/:id/invoke-child.',
    payloadTypes: ['InvokeChildStudioBody', 'StudioContextPacket'],
    trigger: 'Create child Studio from flow selection.',
    why: 'Child studios branch from parent exploration paths.',
  }),
  definePipe({
    id: 'pipe-flowEditor-apiFlows',
    source: 'flowEditor',
    target: 'apiFlows',
    pipeLabel: 'save flow',
    dataFlow: 'Nodes/edges/paths snapshot with expectedRevision CAS.',
    payloadTypes: ['FlowDocumentPayload'],
    trigger: 'Autosave or flushSave after node projection.',
    why: 'Flow edits persist separately from canvas layout.',
  }),
  definePipe({
    id: 'pipe-apiFlows-dbFlowDocument',
    source: 'apiFlows',
    target: 'dbFlowDocument',
    pipeLabel: 'persist flow',
    dataFlow: 'Replaces flow_node/flow_edge rows; bumps revision.',
    payloadTypes: ['flow_document row', 'flow_node rows'],
    trigger: 'Successful PUT /flows/:id or archive removes child node.',
    why: 'Exploration authority is flow_document tables.',
  }),
  definePipe({
    id: 'pipe-apiStudios-apiFlows-restore',
    source: 'apiStudios',
    target: 'apiFlows',
    pipeLabel: 'restore flow node',
    dataFlow: 'Restore re-inserts child studio node on parent primary flow when missing.',
    payloadTypes: ['flow_node row'],
    trigger: 'POST /studios/:id/restore for child with parent.',
    why: 'Archive removed parent flow node server-side; restore heals graph.',
  }),
  definePipe({
    id: 'pipe-apiAgentTemplates-dbAgentTemplate',
    source: 'apiAgentTemplates',
    target: 'dbAgentTemplate',
    pipeLabel: 'persist template',
    dataFlow: 'Template header + file rows with revision CAS.',
    payloadTypes: ['agent_template row'],
    trigger: 'PUT /agent/templates/:id.',
    why: 'Templates are versioned in Postgres.',
  }),
  definePipe({
    id: 'pipe-agentControlRoom-resolveAgentReferenceImages',
    source: 'agentControlRoom',
    target: 'resolveAgentReferenceImages',
    pipeLabel: 'resolve references',
    dataFlow: 'Reference artifact ids resolved to transient dataUrl payloads.',
    payloadTypes: ['ReferenceImage[]'],
    trigger: 'User clicks Run on image agent card.',
    why: 'Execute request includes inline reference bytes without project JSON mutation.',
  }),
  definePipe({
    id: 'pipe-agentControlRoom-apiAgents',
    source: 'agentControlRoom',
    target: 'apiAgents',
    pipeLabel: 'POST /api/agents/:id/execute',
    dataFlow: 'Prompt note id, reference ids/images, and transformer settings.',
    payloadTypes: ['AgentExecuteRequest'],
    trigger: 'User clicks Run after references resolve.',
    why: 'Server runs image generation transformer for the agent artifact.',
  }),
  definePipe({
    id: 'pipe-apiAgents-agentExecutionRunner',
    source: 'apiAgents',
    target: 'agentExecutionRunner',
    pipeLabel: 'run execution',
    dataFlow: 'Validated execute body handed to execution orchestrator.',
    payloadTypes: ['AgentExecuteRequest'],
    trigger: 'POST /api/agents/:id/execute handler.',
    why: 'Route delegates to shared execution runner service.',
  }),
  definePipe({
    id: 'pipe-agentExecutionRunner-imageTransformer',
    source: 'agentExecutionRunner',
    target: 'imageTransformer',
    pipeLabel: 'transform image',
    dataFlow: 'Compiled agent prompt, settings, references, and API key.',
    payloadTypes: ['ImageTransformerRequest'],
    trigger: 'Execution started with transformer_image_generation.',
    why: 'Provider-specific image APIs are isolated in the transformer.',
  }),
  definePipe({
    id: 'pipe-imageTransformer-gemini',
    source: 'imageTransformer',
    target: 'gemini',
    pipeLabel: 'Gemini generateContent',
    dataFlow: 'Prompt parts and generation config to Google image API.',
    payloadTypes: ['GeminiImageRequest'],
    trigger: 'Agent settings provider is gemini.',
    why: 'Gemini image models use generativelanguage.googleapis.com.',
  }),
  definePipe({
    id: 'pipe-imageTransformer-openaiImage',
    source: 'imageTransformer',
    target: 'openaiImage',
    pipeLabel: 'OpenAI image API',
    dataFlow: 'Prompt and reference images to GPT Image or DALL·E endpoints.',
    payloadTypes: ['OpenAIImageRequest'],
    trigger: 'Agent settings provider is openai.',
    why: 'OpenAI image generation uses separate APIs from chat completions.',
  }),
  definePipe({
    id: 'pipe-agentExecutionRunner-dbAgentExecution',
    source: 'agentExecutionRunner',
    target: 'dbAgentExecution',
    pipeLabel: 'persist execution',
    dataFlow: 'execution row, relationships, and generated image artifact inserts.',
    payloadTypes: ['execution row', 'artifact rows'],
    trigger: 'Successful or failed transformer run.',
    why: 'Runs and outputs are queryable execution history.',
  }),
  definePipe({
    id: 'pipe-agentExecutionRunner-dbArtifact',
    source: 'agentExecutionRunner',
    target: 'dbArtifact',
    pipeLabel: 'image artifacts',
    dataFlow: 'Generated image artifact rows with content_hash and metadata.',
    payloadTypes: ['artifact row'],
    trigger: 'Transformer returns image bytes.',
    why: 'Outputs join the primitives artifact graph.',
  }),
  definePipe({
    id: 'pipe-apiAgents-completeAgentImageGeneration',
    source: 'apiAgents',
    target: 'completeAgentImageGeneration',
    pipeLabel: 'execution response',
    dataFlow: 'Completed execution with output artifact metadata returned to client.',
    payloadTypes: ['ExecutionResponse'],
    trigger: 'Successful POST /api/agents/:id/execute.',
    why: 'Client places folder-backed cards and wires graph relationships.',
  }),
  definePipe({
    id: 'pipe-completeAgentImageGeneration-userFolder',
    source: 'completeAgentImageGeneration',
    target: 'userFolder',
    pipeLabel: 'write generated PNG',
    dataFlow: 'generated/{agentSlug}/… paths written to linked folder.',
    payloadTypes: ['BinaryFileWrite'],
    trigger: 'Folder linked after successful execute.',
    why: 'Generated images are folder-canonical like other artifacts.',
  }),
  definePipe({
    id: 'pipe-completeAgentImageGeneration-useCanvasDocument',
    source: 'completeAgentImageGeneration',
    target: 'useCanvasDocument',
    pipeLabel: 'place image cards',
    dataFlow: 'Appends image cards beside agent card with preview metadata.',
    payloadTypes: ['CanvasCard[]'],
    trigger: 'onAddOutputCards after folder persist.',
    why: 'Canvas document hook owns new card placement.',
  }),
  definePipe({
    id: 'pipe-completeAgentImageGeneration-apiPrimitives',
    source: 'completeAgentImageGeneration',
    target: 'apiPrimitives',
    pipeLabel: 'created_by_agent wires',
    dataFlow: 'POST /relationships for agent artifact → each output image.',
    payloadTypes: ['RelationshipMutation'],
    trigger: 'Cluster id resolved after card placement.',
    why: 'Mirrors manual canvas drag wiring for agent outputs.',
  }),
];
